const REVIEWED = '2026-08-22';

const GUIDE_CONTENT_BATCH3 = {
  twitter: {
    reviewed: REVIEWED,
    en: { title: 'Delete X (Twitter) Account Permanently: 30-Day Deactivation Guide', description: 'Delete an X account by using the 30-day deactivation process, download your X archive first, revoke third-party access, and review paid subscriptions.', heading: 'Delete an X account without accidentally reactivating it', overview: 'X uses deactivation as the first step toward permanent account deletion. The account remains recoverable for 30 days, so logging in again during that window reverses the deletion process.', points: ['X states that deactivation starts a 30-day window; if you do not access the account during that period, the account is permanently deleted.', 'Request and download your X data before deactivation if you want an archive. X says the archive should be requested before the account is deactivated.', 'Revoke third-party app access before deactivation because an authorized app can indirectly log in and reactivate the account. Review paid subscriptions separately, especially those purchased through an app store.'] },
    ar: { title: 'حذف حساب X (Twitter) نهائياً: دليل فترة التعطيل 30 يوماً', description: 'احذف حساب X عبر فترة التعطيل التي تستمر 30 يوماً، ونزّل أرشيفك وألغِ وصول التطبيقات الخارجية وراجع الاشتراكات المدفوعة أولاً.', heading: 'حذف حساب X بدون إعادة تنشيطه بالخطأ', overview: 'يستخدم X التعطيل كخطوة أولى نحو الحذف النهائي. يبقى الحساب قابلاً للاستعادة لمدة 30 يوماً، لذلك تسجيل الدخول خلال هذه الفترة يلغي عملية الحذف.', points: ['توضح X أن التعطيل يبدأ فترة 30 يوماً، وإذا لم تدخل إلى الحساب خلالها يتم حذف الحساب نهائياً.', 'اطلب أرشيف بيانات X ونزّله قبل التعطيل إذا كنت تريد الاحتفاظ بنسخة؛ توصي X بطلب البيانات قبل تعطيل الحساب.', 'ألغِ وصول التطبيقات الخارجية قبل التعطيل لأن تطبيقاً مصرحاً له قد يسجل الدخول بشكل غير مباشر ويعيد تنشيط الحساب. راجع الاشتراكات المدفوعة بشكل منفصل، خصوصاً المشتراة عبر متجر التطبيقات.'] },
    fr: { title: 'Supprimer définitivement X (Twitter) : désactivation de 30 jours | Guide', description: 'Supprimez un compte X via la période de désactivation de 30 jours, téléchargez l’archive et révoquez les applications tierces avant de partir.', heading: 'Supprimer X sans réactiver le compte par erreur', overview: 'X utilise la désactivation comme première étape de la suppression définitive. Le compte reste récupérable pendant 30 jours et toute nouvelle connexion pendant cette période annule la suppression.', points: ['X indique que la désactivation ouvre une période de 30 jours ; sans accès au compte pendant ce délai, le compte est supprimé définitivement.', 'Demandez et téléchargez votre archive X avant la désactivation si vous souhaitez conserver vos données.', 'Révoquez les applications tierces avant la désactivation, car une application autorisée peut se reconnecter et réactiver le compte. Vérifiez aussi les abonnements payants séparément.'] },
    tr: { title: 'X (Twitter) Hesabını Kalıcı Silme: 30 Günlük Devre Dışı Bırakma Rehberi', description: 'X hesabını 30 günlük devre dışı bırakma süreciyle silin; önce arşivinizi indirin, üçüncü taraf erişimini kaldırın ve abonelikleri kontrol edin.', heading: 'X hesabını yanlışlıkla yeniden etkinleştirmeden silin', overview: 'X, kalıcı silmenin ilk adımı olarak hesabı devre dışı bırakır. Hesap 30 gün boyunca geri alınabilir; bu süre içinde tekrar giriş yapmak silme işlemini iptal eder.', points: ['X, devre dışı bırakmanın 30 günlük bir dönem başlattığını ve bu sürede hesaba erişilmezse hesabın kalıcı olarak silindiğini belirtir.', 'Verilerinizi saklamak istiyorsanız devre dışı bırakmadan önce X arşivinizi talep edip indirin.', 'Yetkili bir üçüncü taraf uygulama dolaylı olarak giriş yapıp hesabı yeniden etkinleştirebileceği için uygulama erişimlerini kaldırın. Özellikle uygulama mağazası üzerinden alınan ücretli abonelikleri ayrıca kontrol edin.'] }
  },
  linkedin: {
    reviewed: REVIEWED,
    en: { title: 'Delete LinkedIn Account Permanently vs Hibernate | Data & Profile Guide', description: 'Close a LinkedIn account, compare permanent closure with hibernation, download data first, and understand what may remain visible after closure.', heading: 'Close LinkedIn permanently or hibernate it instead', overview: 'LinkedIn offers hibernation as a reversible alternative to account closure. Permanent closure removes access to the account and starts LinkedIn’s deletion process for account data.', points: ['LinkedIn says you can hibernate the account instead of closing it if you want a reversible break.', 'LinkedIn says closed-account information is generally deleted within 30 days, while the profile generally stops being visible to others within 24 hours.', 'Content shared with other members, such as some messages, updates or group posts, can remain visible after closure. Download data and remove content you specifically need gone before closing the account.'] },
    ar: { title: 'حذف حساب LinkedIn نهائياً أم إسباته؟ دليل البيانات والملف الشخصي', description: 'أغلق حساب LinkedIn أو استخدم الإسبات كخيار قابل للرجوع، ونزّل بياناتك وافهم ما قد يبقى ظاهراً بعد الإغلاق.', heading: 'إغلاق LinkedIn نهائياً أو إسبات الحساب بدلاً من ذلك', overview: 'يوفر LinkedIn الإسبات كبديل قابل للتراجع عن إغلاق الحساب. الإغلاق النهائي يوقف الوصول للحساب ويبدأ عملية حذف بيانات الحساب.', points: ['توضح LinkedIn أنه يمكن إسبات الحساب بدلاً من إغلاقه عندما تريد استراحة قابلة للرجوع.', 'بحسب LinkedIn، يتم حذف معلومات الحساب المغلق عادة خلال 30 يوماً، بينما يتوقف الملف الشخصي عادة عن الظهور للآخرين خلال 24 ساعة.', 'قد يبقى بعض المحتوى الذي شاركته مع الآخرين، مثل الرسائل أو التحديثات أو منشورات المجموعات، ظاهراً بعد الإغلاق. نزّل بياناتك واحذف المحتوى المحدد الذي تريد إزالته قبل إغلاق الحساب.'] },
    fr: { title: 'Supprimer LinkedIn définitivement ou mettre le compte en veille | Guide', description: 'Fermez LinkedIn ou utilisez la mise en veille, téléchargez vos données et comprenez ce qui peut rester visible après la fermeture.', heading: 'Fermer LinkedIn définitivement ou mettre le compte en veille', overview: 'LinkedIn propose la mise en veille comme alternative réversible à la fermeture. La fermeture définitive coupe l’accès au compte et lance la suppression des données du compte.', points: ['LinkedIn indique que vous pouvez mettre le compte en veille au lieu de le fermer si vous souhaitez une pause réversible.', 'LinkedIn indique que les informations du compte fermé sont généralement supprimées sous 30 jours et que le profil cesse généralement d’être visible aux autres sous 24 heures.', 'Certains contenus partagés avec d’autres membres peuvent rester visibles après la fermeture. Téléchargez vos données et supprimez les éléments précis que vous souhaitez retirer avant de fermer le compte.'] },
    tr: { title: 'LinkedIn Hesabını Kalıcı Silme veya Hazırda Bekletme | Veri Rehberi', description: 'LinkedIn hesabını kapatın veya geri dönüşlü hazırda bekletmeyi seçin; önce verilerinizi indirin ve kapanış sonrası kalabilecek içerikleri öğrenin.', heading: 'LinkedIn hesabını kalıcı kapatın veya hazırda bekletin', overview: 'LinkedIn, hesabı kapatmaya geri dönüşlü bir alternatif olarak hazırda bekletme seçeneği sunar. Kalıcı kapatma hesaba erişimi sona erdirir ve hesap verilerinin silinme sürecini başlatır.', points: ['LinkedIn, geri dönebileceğiniz bir ara istiyorsanız hesabı kapatmak yerine hazırda bekletebileceğinizi belirtir.', 'LinkedIn’e göre kapatılan hesap bilgileri genellikle 30 gün içinde silinir ve profil genellikle 24 saat içinde diğer kişilere görünmez olur.', 'Diğer üyelerle paylaşılan bazı mesaj, güncelleme veya grup gönderileri kapanıştan sonra görünür kalabilir. Kapatmadan önce verilerinizi indirin ve özellikle kaldırmak istediğiniz içeriği silin.'] }
  },
  paypal: {
    reviewed: REVIEWED,
    en: { title: 'Delete PayPal Account & Personal Data: Balance, Payments and Retention Guide', description: 'Close PayPal safely, clear balances and outstanding payments, download data first, and understand why some financial records may be retained.', heading: 'Close PayPal only after clearing money and account obligations', overview: 'PayPal account closure and personal-data erasure are closely linked, but financial and legal retention rules can affect what is removed and when.', points: ['PayPal requires outstanding payments to be cleared before account closure and data erasure; transfer any remaining eligible balance before closing the account.', 'PayPal’s privacy controls can provide a data copy and a Delete your data / close account flow. PayPal states that the account must be closed before it can delete the associated data.', 'Some information may be retained for legal, regulatory, fraud-prevention, dispute or security reasons even after account closure. Once eligible data is erased, PayPal says it cannot be recovered.'] },
    ar: { title: 'حذف حساب PayPal والبيانات: الرصيد والمدفوعات والاحتفاظ | دليل', description: 'أغلق PayPal بأمان بعد تصفية الرصيد والمدفوعات، ونزّل بياناتك وافهم لماذا قد تُحتفظ بعض السجلات المالية.', heading: 'إغلاق PayPal بعد تصفية الرصيد والالتزامات', overview: 'إغلاق حساب PayPal وحذف البيانات الشخصية مرتبطان ببعضهما، لكن قواعد الاحتفاظ المالية والقانونية تؤثر على البيانات التي يمكن حذفها وموعد حذفها.', points: ['يتطلب PayPal تسوية المدفوعات المستحقة قبل إغلاق الحساب وحذف البيانات؛ انقل أي رصيد مؤهل متبقٍ قبل الإغلاق.', 'توفر إعدادات الخصوصية في PayPal تنزيل نسخة من البيانات ومسار حذف البيانات/إغلاق الحساب. ويوضح PayPal أن الحساب يجب أن يكون مغلقاً قبل حذف البيانات المرتبطة به.', 'قد يحتفظ PayPal ببعض المعلومات لأسباب قانونية أو تنظيمية أو لمنع الاحتيال وحل النزاعات والأمان. وبعد حذف البيانات المؤهلة لا يمكن استعادتها.'] },
    fr: { title: 'Supprimer PayPal et les données personnelles : solde, paiements et conservation | Guide', description: 'Fermez PayPal après avoir réglé soldes et paiements, téléchargez vos données et comprenez les obligations de conservation financière.', heading: 'Fermer PayPal après avoir réglé le solde et les obligations du compte', overview: 'La fermeture du compte PayPal et l’effacement des données sont liés, mais des règles financières et légales peuvent imposer la conservation de certaines informations.', points: ['PayPal demande de régler les paiements en attente avant la fermeture et l’effacement ; transférez le solde restant éligible avant de fermer.', 'Les paramètres de confidentialité PayPal permettent de télécharger des données et d’utiliser le parcours de suppression des données / fermeture du compte. PayPal indique que le compte doit être fermé avant l’effacement associé.', 'Certaines informations peuvent être conservées pour des raisons légales, réglementaires, de prévention de la fraude, de litige ou de sécurité. Les données effectivement effacées ne sont ensuite pas récupérables.'] },
    tr: { title: 'PayPal Hesabını ve Kişisel Verileri Silme: Bakiye, Ödeme ve Saklama Rehberi', description: 'PayPal hesabını kapatmadan önce bakiye ve ödemeleri temizleyin, verilerinizi indirin ve finansal kayıtların neden saklanabileceğini öğrenin.', heading: 'PayPal hesabını para ve yükümlülükleri temizledikten sonra kapatın', overview: 'PayPal hesabını kapatma ile kişisel veri silme birbiriyle bağlantılıdır; ancak finansal ve yasal saklama kuralları bazı bilgilerin ne zaman kaldırılacağını etkileyebilir.', points: ['PayPal, hesap kapatma ve veri silmeden önce bekleyen ödemelerin çözülmesini ister; kalan uygun bakiyeyi kapatmadan önce aktarın.', 'PayPal gizlilik kontrolleri veri kopyası indirme ve Verilerinizi silin / hesabı kapatın akışı sunar. PayPal, ilişkili verilerin silinebilmesi için hesabın kapatılması gerektiğini belirtir.', 'Yasal, düzenleyici, dolandırıcılık önleme, uyuşmazlık veya güvenlik nedenleriyle bazı bilgiler tutulabilir. Uygun veriler silindikten sonra PayPal bunların geri getirilemeyeceğini belirtir.'] }
  },
  netflix: {
    reviewed: REVIEWED,
    en: { title: 'Delete Netflix Account vs Cancel Membership: Profiles, Billing & Data Guide', description: 'Understand Netflix account deletion versus canceling membership, partner billing, profile deletion and retained account data before making a permanent change.', heading: 'Delete Netflix only after separating account deletion from membership cancellation', overview: 'Netflix treats membership cancellation, account deletion, profile deletion and viewing-history removal as different actions. Choose the narrowest action that matches what you actually want removed.', points: ['Netflix says signing out or deleting the Netflix app does not cancel membership. Use the membership cancellation control or the billing partner shown on your account.', 'Netflix provides separate controls and help for account deletion, profiles, viewing history, payment methods, phone numbers and email addresses; deleting one is not automatically the same as deleting the whole account.', 'Netflix states that some personal information may be retained where required or permitted by law. If billing is through a partner, cancel with that payment partner when Netflix directs you to do so.'] },
    ar: { title: 'حذف حساب Netflix أم إلغاء الاشتراك؟ دليل الملفات والفوترة والبيانات', description: 'افهم الفرق بين حذف حساب Netflix وإلغاء الاشتراك وحذف الملفات وسجل المشاهدة، وراجع الفوترة عبر الشركاء قبل أي إجراء نهائي.', heading: 'حذف Netflix بعد التفريق بين حذف الحساب وإلغاء الاشتراك', overview: 'يتعامل Netflix مع إلغاء العضوية وحذف الحساب وحذف الملف الشخصي وسجل المشاهدة كإجراءات مختلفة. اختر الإجراء الذي يطابق ما تريد إزالته فعلاً.', points: ['توضح Netflix أن تسجيل الخروج أو حذف التطبيق لا يلغي العضوية. استخدم خيار إلغاء العضوية أو جهة الفوترة الشريكة الظاهرة في حسابك.', 'توفر Netflix إجراءات منفصلة لحذف الحساب والملفات وسجل المشاهدة وطرق الدفع ورقم الهاتف والبريد، لذلك حذف أحدها ليس نفس حذف الحساب بالكامل.', 'قد تحتفظ Netflix ببعض المعلومات الشخصية عندما يفرض القانون أو يسمح بذلك. وإذا كانت الفوترة عبر شريك، فاتبع تعليمات Netflix للإلغاء من خلال ذلك الشريك.'] },
    fr: { title: 'Supprimer Netflix ou annuler l’abonnement : profils, facturation et données | Guide', description: 'Distinguez suppression du compte Netflix, annulation de l’abonnement, profils, historique et facturation partenaire avant une action définitive.', heading: 'Supprimer Netflix après avoir séparé suppression du compte et résiliation', overview: 'Netflix traite la résiliation, la suppression du compte, les profils et l’historique de visionnage comme des actions différentes. Choisissez l’action la plus précise.', points: ['Netflix indique que se déconnecter ou supprimer l’application ne résilie pas l’abonnement. Utilisez la commande de résiliation ou le partenaire de facturation indiqué sur le compte.', 'Netflix propose des contrôles séparés pour le compte, les profils, l’historique, les moyens de paiement, le téléphone et l’e-mail ; supprimer un élément ne supprime pas automatiquement tout le compte.', 'Netflix peut conserver certaines informations lorsque la loi l’exige ou l’autorise. Si la facturation passe par un partenaire, suivez les instructions de Netflix pour résilier auprès de ce partenaire.'] },
    tr: { title: 'Netflix Hesabını Silme veya Üyeliği İptal Etme: Profil, Fatura ve Veri Rehberi', description: 'Netflix hesabını silme ile üyelik iptali, profil silme ve izleme geçmişi arasındaki farkı öğrenin; partner faturalandırmasını kontrol edin.', heading: 'Netflix hesabını üyelik iptaliyle karıştırmadan silin', overview: 'Netflix üyelik iptali, hesap silme, profil silme ve izleme geçmişini ayrı işlemler olarak ele alır. Gerçekte kaldırmak istediğiniz şeye uygun en dar işlemi seçin.', points: ['Netflix, oturumu kapatmanın veya uygulamayı silmenin üyeliği iptal etmediğini belirtir. Üyelik iptal kontrolünü veya hesapta gösterilen ödeme ortağını kullanın.', 'Netflix hesap silme, profiller, izleme geçmişi, ödeme yöntemleri, telefon ve e-posta için ayrı kontroller sunar; birini silmek tüm hesabı silmek değildir.', 'Netflix, yasaların gerektirdiği veya izin verdiği durumlarda bazı kişisel bilgileri saklayabilir. Faturalandırma bir partner üzerinden yapılıyorsa Netflix’in yönlendirdiği partner üzerinden iptal edin.'] }
  },
  dropbox: {
    reviewed: REVIEWED,
    en: { title: 'Delete Dropbox Account Safely: Files, Shared Folders & Subscription Guide', description: 'Delete Dropbox safely, cancel paid plans first, back up important files, and understand what happens to synced and shared content.', heading: 'Delete Dropbox without losing files you still need', overview: 'Dropbox account deletion can permanently remove private cloud data and stop syncing across devices, while shared-folder content can behave differently.', points: ['Dropbox says an active paid subscription must be canceled before account deletion can proceed.', 'After account deletion, private account and file data are deleted and cannot be restored; synced copies already stored on a computer can remain locally but stop syncing.', 'Files in shared folders can remain accessible to other members even after your account is deleted. Back up needed content and review team or Family responsibilities before deletion.'] },
    ar: { title: 'حذف حساب Dropbox بأمان: الملفات والمجلدات المشتركة والاشتراك | دليل', description: 'احذف Dropbox بعد إلغاء الخطة المدفوعة ونسخ الملفات المهمة، وافهم ما يحدث للمحتوى المتزامن والمشترك.', heading: 'حذف Dropbox بدون خسارة ملفات تحتاجها', overview: 'حذف حساب Dropbox قد يزيل بيانات السحابة الخاصة نهائياً ويوقف المزامنة، بينما قد يتصرف المحتوى داخل المجلدات المشتركة بشكل مختلف.', points: ['توضح Dropbox أن الاشتراك المدفوع النشط يجب إلغاؤه قبل إكمال حذف الحساب.', 'بعد حذف الحساب تُحذف بيانات الحساب والملفات الخاصة ولا يمكن استعادتها؛ النسخ المتزامنة الموجودة مسبقاً على الكمبيوتر قد تبقى محلياً لكنها تتوقف عن المزامنة.', 'قد تبقى الملفات في المجلدات المشتركة متاحة للأعضاء الآخرين بعد حذف حسابك. انسخ المحتوى المهم وراجع مسؤوليات الفريق أو Family قبل الحذف.'] },
    fr: { title: 'Supprimer Dropbox : fichiers, dossiers partagés et abonnement | Guide', description: 'Supprimez Dropbox après avoir annulé le forfait payant et sauvegardé les fichiers importants, puis vérifiez les dossiers partagés.', heading: 'Supprimer Dropbox sans perdre les fichiers à conserver', overview: 'La suppression du compte Dropbox peut retirer définitivement les données cloud privées et arrêter la synchronisation, tandis que le contenu partagé peut rester accessible aux autres membres.', points: ['Dropbox indique qu’un abonnement payant actif doit être annulé avant de pouvoir supprimer le compte.', 'Après suppression, les données privées du compte et des fichiers sont supprimées et non récupérables ; les copies déjà synchronisées sur un ordinateur peuvent rester localement mais cessent de se synchroniser.', 'Les fichiers présents dans des dossiers partagés peuvent rester accessibles aux autres membres. Sauvegardez le contenu utile et vérifiez les responsabilités d’équipe ou Family avant suppression.'] },
    tr: { title: 'Dropbox Hesabını Güvenle Silme: Dosyalar, Paylaşılan Klasörler ve Abonelik | Rehber', description: 'Dropbox hesabını silmeden önce ücretli planı iptal edin, önemli dosyaları yedekleyin ve paylaşılan içeriklere ne olacağını öğrenin.', heading: 'Saklamak istediğiniz dosyaları kaybetmeden Dropbox hesabını silin', overview: 'Dropbox hesabını silmek özel bulut verilerini kalıcı olarak kaldırabilir ve cihazlar arası eşitlemeyi durdurabilir; paylaşılan klasörlerdeki içerikler ise farklı davranabilir.', points: ['Dropbox, etkin ücretli aboneliğin hesap silme işleminden önce iptal edilmesi gerektiğini belirtir.', 'Hesap silindikten sonra özel hesap ve dosya verileri silinir ve geri alınamaz; bilgisayarda önceden eşitlenmiş kopyalar yerel olarak kalabilir ancak eşitleme durur.', 'Paylaşılan klasörlerdeki dosyalar diğer üyeler tarafından erişilebilir kalabilir. Silmeden önce gerekli içeriği yedekleyin ve ekip veya Family sorumluluklarını kontrol edin.'] }
  },
  adobe: {
    reviewed: REVIEWED,
    en: { title: 'Delete Adobe Account Permanently: Creative Cloud Files, Plans & 27-Day Recovery', description: 'Delete an Adobe account after backing up cloud files, canceling plans and transferring admin roles, with Adobe’s current 27-day reactivation window.', heading: 'Delete Adobe only after backing up Creative Cloud data and plans', overview: 'Adobe account deletion removes access to apps, cloud files, purchase history, invoices and account settings, so subscriptions and organization responsibilities should be resolved first.', points: ['Adobe says to back up cloud files, cancel active subscriptions, transfer organization admin roles and leave associated organizations before deleting the account.', 'Deleting the Adobe account removes access to Adobe apps and services, cloud-stored files, purchase history, invoices and account settings.', 'Adobe currently states that an account can be reactivated within 27 days of deletion; after that, the account data is permanently deleted and cannot be retrieved.'] },
    ar: { title: 'حذف حساب Adobe نهائياً: ملفات Creative Cloud والخطط وفترة 27 يوماً', description: 'احذف Adobe بعد نسخ ملفات السحابة وإلغاء الخطط ونقل صلاحيات الإدارة، مع فهم نافذة إعادة التنشيط الحالية التي تبلغ 27 يوماً.', heading: 'حذف Adobe بعد نسخ بيانات Creative Cloud ومعالجة الخطط', overview: 'حذف حساب Adobe يزيل الوصول إلى التطبيقات والملفات السحابية وسجل المشتريات والفواتير والإعدادات، لذلك يجب معالجة الاشتراكات ومسؤوليات المنظمات أولاً.', points: ['توصي Adobe بنسخ ملفات السحابة وإلغاء الاشتراكات النشطة ونقل أدوار إدارة المنظمات ومغادرة المنظمات المرتبطة قبل حذف الحساب.', 'حذف حساب Adobe يزيل الوصول إلى تطبيقات وخدمات Adobe والملفات المخزنة سحابياً وسجل المشتريات والفواتير وإعدادات الحساب.', 'توضح Adobe حالياً أنه يمكن إعادة تنشيط الحساب خلال 27 يوماً من الحذف؛ بعد ذلك تُحذف البيانات نهائياً ولا يمكن استعادتها.'] },
    fr: { title: 'Supprimer Adobe : fichiers Creative Cloud, abonnements et récupération 27 jours | Guide', description: 'Supprimez Adobe après avoir sauvegardé les fichiers cloud, annulé les abonnements et transféré les rôles administrateur, avec la fenêtre de 27 jours.', heading: 'Supprimer Adobe après avoir sauvegardé Creative Cloud et réglé les abonnements', overview: 'La suppression du compte Adobe retire l’accès aux applications, fichiers cloud, achats, factures et paramètres. Réglez donc les abonnements et responsabilités d’organisation avant de supprimer.', points: ['Adobe recommande de sauvegarder les fichiers cloud, d’annuler les abonnements actifs, de transférer les rôles administrateur et de quitter les organisations associées avant suppression.', 'La suppression retire l’accès aux applications et services Adobe, aux fichiers cloud, à l’historique d’achat, aux factures et aux paramètres du compte.', 'Adobe indique actuellement que le compte peut être réactivé pendant 27 jours après la suppression ; ensuite les données sont supprimées définitivement et ne peuvent plus être récupérées.'] },
    tr: { title: 'Adobe Hesabını Kalıcı Silme: Creative Cloud Dosyaları, Planlar ve 27 Günlük Kurtarma', description: 'Adobe hesabını silmeden önce bulut dosyalarını yedekleyin, planları iptal edin ve yönetici rollerini aktarın; 27 günlük yeniden etkinleştirme süresini bilin.', heading: 'Creative Cloud verilerini ve planları güvenceye aldıktan sonra Adobe hesabını silin', overview: 'Adobe hesabını silmek uygulamalara, bulut dosyalarına, satın alma geçmişine, faturalara ve ayarlara erişimi kaldırır; bu nedenle abonelikleri ve organizasyon sorumluluklarını önce çözün.', points: ['Adobe, hesabı silmeden önce bulut dosyalarını yedeklemeyi, aktif abonelikleri iptal etmeyi, organizasyon yönetici rollerini devretmeyi ve ilişkili organizasyonlardan ayrılmayı önerir.', 'Adobe hesabını silmek Adobe uygulama ve hizmetlerine, bulut dosyalarına, satın alma geçmişine, faturalara ve hesap ayarlarına erişimi kaldırır.', 'Adobe şu anda hesabın silindikten sonra 27 gün içinde yeniden etkinleştirilebildiğini; bu süreden sonra verilerin kalıcı olarak silindiğini belirtir.'] }
  },
  slack: {
    reviewed: REVIEWED,
    en: { title: 'Delete or Deactivate Slack Account: Workspaces, Messages & Profile Data | Guide', description: 'Leave Slack safely by understanding workspace-by-workspace deactivation, message retention, primary-owner restrictions and profile-data deletion.', heading: 'Deactivate Slack workspace accounts and handle profile data separately', overview: 'Slack identities are workspace-scoped. Deactivating one workspace account does not automatically remove every Slack membership or erase messages and files you previously sent.', points: ['Slack says messages and files you sent are not deleted when you deactivate an account; remove allowed content before deactivation if that matters to you.', 'If you belong to multiple workspaces, Slack requires each workspace account to be deactivated separately. A Workspace Primary Owner must transfer primary ownership before deactivating.', 'Profile-information deletion is separate from account deactivation. Slack says you can ask the Workspace Primary Owner to delete profile information after the account is deactivated.'] },
    ar: { title: 'حذف أو تعطيل حساب Slack: مساحات العمل والرسائل وبيانات الملف | دليل', description: 'غادر Slack بأمان عبر فهم التعطيل لكل مساحة عمل واحتفاظ الرسائل وقيود المالك الأساسي وحذف بيانات الملف الشخصي.', heading: 'تعطيل حسابات Slack لكل مساحة عمل ومعالجة بيانات الملف بشكل منفصل', overview: 'حسابات Slack مرتبطة بمساحات العمل. تعطيل حساب في مساحة واحدة لا يزيل تلقائياً كل عضويات Slack ولا يمحو الرسائل والملفات التي أرسلتها.', points: ['توضح Slack أن الرسائل والملفات التي أرسلتها لا تُحذف عند تعطيل الحساب؛ احذف المحتوى المسموح لك بحذفه قبل التعطيل إذا كان ذلك مهماً.', 'إذا كنت عضواً في عدة مساحات عمل، يجب تعطيل كل حساب مساحة بشكل منفصل. ويجب على المالك الأساسي نقل الملكية قبل تعطيل حسابه.', 'حذف معلومات الملف الشخصي منفصل عن تعطيل الحساب. توضح Slack أنه يمكن طلب حذف معلومات الملف من المالك الأساسي بعد تعطيل الحساب.'] },
    fr: { title: 'Supprimer ou désactiver Slack : espaces de travail, messages et profil | Guide', description: 'Quittez Slack en comprenant la désactivation par espace, la conservation des messages, les restrictions du propriétaire principal et la suppression du profil.', heading: 'Désactiver Slack par espace de travail et gérer séparément les données de profil', overview: 'Les identités Slack sont liées aux espaces de travail. Désactiver un compte dans un espace ne supprime pas automatiquement les autres appartenances ni les messages et fichiers déjà envoyés.', points: ['Slack indique que les messages et fichiers envoyés ne sont pas supprimés lors de la désactivation ; supprimez au préalable le contenu que vos paramètres vous autorisent à retirer.', 'Si vous appartenez à plusieurs espaces, chaque compte doit être désactivé séparément. Le propriétaire principal doit transférer la propriété avant de désactiver son compte.', 'La suppression des informations de profil est distincte de la désactivation. Slack indique qu’un propriétaire principal peut supprimer les informations de profil après désactivation.'] },
    tr: { title: 'Slack Hesabını Silme veya Devre Dışı Bırakma: Çalışma Alanları ve Profil Verisi', description: 'Slack’ten ayrılırken çalışma alanı bazlı devre dışı bırakmayı, mesaj saklamayı, ana sahip kısıtlarını ve profil verisi silmeyi anlayın.', heading: 'Slack çalışma alanı hesaplarını devre dışı bırakın ve profil verisini ayrı yönetin', overview: 'Slack kimlikleri çalışma alanı bazlıdır. Bir çalışma alanındaki hesabı devre dışı bırakmak diğer Slack üyeliklerini veya daha önce gönderdiğiniz mesaj ve dosyaları otomatik olarak silmez.', points: ['Slack, hesabı devre dışı bıraktığınızda gönderdiğiniz mesaj ve dosyaların silinmediğini belirtir; önemliyse izin verilen içeriği önce silin.', 'Birden fazla çalışma alanındaysanız her hesap ayrı ayrı devre dışı bırakılmalıdır. Workspace Primary Owner, hesabını devre dışı bırakmadan önce ana sahipliği devretmelidir.', 'Profil bilgilerini silme, hesap devre dışı bırakmadan ayrıdır. Slack, hesap devre dışı bırakıldıktan sonra Primary Owner’dan profil bilgilerinin silinmesini isteyebileceğinizi belirtir.'] }
  },
  zoom: {
    reviewed: REVIEWED,
    en: { title: 'Delete Zoom Account Permanently: Free vs Paid Account Requirements | Guide', description: 'Delete a Zoom account permanently, understand why paid accounts must cancel first, and check owner requirements before terminating the account.', heading: 'Terminate Zoom only after a paid plan has fully ended', overview: 'Zoom account termination is available directly to Basic free accounts. Paid accounts have an additional subscription step before the account itself can be deleted.', points: ['Zoom says Basic free accounts can be deleted at any time and the deletion is permanent.', 'For a paid account, Zoom requires the subscription to be canceled and the current billing cycle to end before the account can be terminated.', 'Zoom lists account Owner role as a requirement for terminating the account. If you manage multiple users, handle those users and ownership responsibilities before deletion.'] },
    ar: { title: 'حذف حساب Zoom نهائياً: متطلبات الحساب المجاني والمدفوع | دليل', description: 'احذف Zoom نهائياً وافهم لماذا يجب إنهاء الاشتراك المدفوع أولاً وراجع متطلبات دور المالك قبل إنهاء الحساب.', heading: 'إنهاء حساب Zoom بعد انتهاء الخطة المدفوعة بالكامل', overview: 'يمكن إنهاء حساب Zoom المجاني Basic مباشرة، بينما يحتاج الحساب المدفوع خطوة إضافية مرتبطة بالاشتراك قبل حذف الحساب نفسه.', points: ['توضح Zoom أن حسابات Basic المجانية يمكن حذفها في أي وقت وأن الحذف نهائي.', 'بالنسبة للحساب المدفوع، تشترط Zoom إلغاء الاشتراك وانتظار نهاية دورة الفوترة الحالية قبل إنهاء الحساب.', 'تذكر Zoom أن دور Owner مطلوب لإنهاء الحساب. إذا كنت تدير عدة مستخدمين، عالج المستخدمين ومسؤوليات الملكية قبل الحذف.'] },
    fr: { title: 'Supprimer Zoom définitivement : conditions compte gratuit ou payant | Guide', description: 'Supprimez Zoom définitivement, comprenez pourquoi un compte payant doit d’abord résilier son abonnement et vérifiez le rôle de propriétaire.', heading: 'Supprimer Zoom après la fin complète d’un abonnement payant', overview: 'La suppression directe est disponible pour les comptes Zoom Basic gratuits. Un compte payant doit d’abord terminer les étapes liées à l’abonnement.', points: ['Zoom indique qu’un compte Basic gratuit peut être supprimé à tout moment et que la suppression est définitive.', 'Pour un compte payant, Zoom exige d’annuler l’abonnement et d’attendre la fin du cycle de facturation en cours avant de supprimer le compte.', 'Zoom indique que le rôle Owner est requis pour supprimer le compte. Si vous administrez plusieurs utilisateurs, traitez leurs comptes et la propriété avant la suppression.'] },
    tr: { title: 'Zoom Hesabını Kalıcı Silme: Ücretsiz ve Ücretli Hesap Gereksinimleri', description: 'Zoom hesabını kalıcı silin; ücretli hesapların neden önce aboneliği bitirmesi gerektiğini ve Owner rolü gereksinimini öğrenin.', heading: 'Ücretli plan tamamen bittikten sonra Zoom hesabını sonlandırın', overview: 'Zoom Basic ücretsiz hesaplar doğrudan sonlandırılabilir. Ücretli hesaplarda hesabın kendisi silinmeden önce abonelikle ilgili ek bir adım vardır.', points: ['Zoom, Basic ücretsiz hesapların her zaman silinebileceğini ve silmenin kalıcı olduğunu belirtir.', 'Ücretli hesaplarda Zoom, hesabın sonlandırılmasından önce aboneliğin iptal edilmesini ve mevcut faturalandırma döneminin bitmesini şart koşar.', 'Zoom, hesabı sonlandırmak için Owner rolünü gereksinim olarak listeler. Birden fazla kullanıcı yönetiyorsanız silmeden önce kullanıcı ve sahiplik sorumluluklarını çözün.'] }
  },
  pinterest: {
    reviewed: REVIEWED,
    en: { title: 'Delete Pinterest Account Permanently vs Deactivate: 7-Day Recovery Guide', description: 'Delete Pinterest permanently or deactivate it temporarily, understand the current 7-day recovery period, and clear business-account billing first.', heading: 'Delete Pinterest permanently or deactivate it for a reversible break', overview: 'Pinterest offers both temporary deactivation and permanent account deletion. Permanent deletion starts by deactivating the public profile and currently includes a short recovery window.', points: ['Pinterest currently says the public profile is immediately deactivated after a deletion request and the account and personal data are permanently deleted in 7 days.', 'If you change your mind before the 7-day period ends, Pinterest says the account can generally be reactivated; temporary deactivation is the better choice when you only want a break.', 'Business accounts with outstanding bills need billing issues cleared before deletion. Download or request any account information you want to keep first.'] },
    ar: { title: 'حذف حساب Pinterest نهائياً أم تعطيله؟ دليل فترة الاستعادة 7 أيام', description: 'احذف Pinterest نهائياً أو عطله مؤقتاً، وافهم فترة الاستعادة الحالية التي تبلغ 7 أيام وصفِّ فوترة الحساب التجاري أولاً.', heading: 'حذف Pinterest نهائياً أو تعطيله لاستراحة قابلة للرجوع', overview: 'يوفر Pinterest التعطيل المؤقت والحذف النهائي كخيارين مختلفين. يبدأ الحذف النهائي بتعطيل الملف العام ويوفر حالياً نافذة استعادة قصيرة.', points: ['توضح Pinterest حالياً أن الملف العام يتعطل فور طلب الحذف وأن الحساب والبيانات الشخصية تُحذف نهائياً خلال 7 أيام.', 'إذا غيرت رأيك قبل انتهاء فترة 7 أيام يمكن عادة إعادة تنشيط الحساب؛ استخدم التعطيل المؤقت إذا كنت تريد استراحة فقط.', 'يجب معالجة الفواتير المستحقة للحسابات التجارية قبل الحذف. اطلب أو نزّل أي معلومات تريد الاحتفاظ بها أولاً.'] },
    fr: { title: 'Supprimer Pinterest ou le désactiver : récupération pendant 7 jours | Guide', description: 'Supprimez Pinterest définitivement ou désactivez-le temporairement, avec la période actuelle de récupération de 7 jours et les règles de facturation Business.', heading: 'Supprimer Pinterest définitivement ou le désactiver pour une pause réversible', overview: 'Pinterest propose désactivation temporaire et suppression définitive. La suppression commence par masquer le profil public et comprend actuellement une courte période de récupération.', points: ['Pinterest indique actuellement que le profil public est désactivé immédiatement et que le compte et les données personnelles sont supprimés définitivement sous 7 jours.', 'Si vous changez d’avis avant la fin des 7 jours, le compte peut généralement être réactivé ; utilisez plutôt la désactivation pour une simple pause.', 'Les comptes Business doivent régler les problèmes de facturation avant suppression. Téléchargez ou demandez auparavant les informations que vous souhaitez conserver.'] },
    tr: { title: 'Pinterest Hesabını Kalıcı Silme veya Devre Dışı Bırakma: 7 Günlük Kurtarma', description: 'Pinterest hesabını kalıcı silin veya geçici kapatın; güncel 7 günlük kurtarma dönemini ve işletme hesabı faturalandırmasını kontrol edin.', heading: 'Pinterest hesabını kalıcı silin veya geri dönüşlü bir ara için devre dışı bırakın', overview: 'Pinterest geçici devre dışı bırakma ile kalıcı silmeyi ayrı seçenekler olarak sunar. Kalıcı silme önce herkese açık profili kapatır ve şu anda kısa bir kurtarma süresi içerir.', points: ['Pinterest şu anda silme talebinden sonra herkese açık profilin hemen devre dışı kaldığını ve hesap ile kişisel verilerin 7 gün içinde kalıcı silindiğini belirtir.', '7 günlük süre dolmadan fikrinizi değiştirirseniz hesap genellikle yeniden etkinleştirilebilir; yalnızca ara vermek istiyorsanız geçici devre dışı bırakmayı kullanın.', 'Ödenmemiş faturası olan işletme hesaplarında silmeden önce faturalandırma sorunları çözülmelidir. Saklamak istediğiniz hesap bilgilerini önce indirin veya talep edin.'] }
  },
  ebay: {
    reviewed: REVIEWED,
    en: { title: 'Close eBay Account Permanently: Pending Transactions, Seller Funds & Data | Guide', description: 'Close eBay safely after resolving bids, payments, returns, disputes, payouts and subscriptions, and understand the current 14-to-60-day closure process.', heading: 'Close eBay only after every transaction and seller obligation is finished', overview: 'eBay account closure affects buying, selling, feedback and account history. Open transactions or seller obligations can delay or block the closure process.', points: ['eBay requires fees and selling costs to be paid, available funds to be zero, subscriptions canceled, and open bids, payments, returns, disputes and payouts resolved before closure.', 'eBay currently says account closure generally takes 14 days, but can take up to 60 days when there were transactions, payments, claims or disputes in the previous 30 days.', 'During the closure period, an eligible account in good standing can generally request that closure be canceled. After final closure, buying/selling access, feedback and purchase/sales history are no longer available.'] },
    ar: { title: 'إغلاق حساب eBay نهائياً: المعاملات المعلقة وأموال البائع والبيانات | دليل', description: 'أغلق eBay بعد إنهاء العروض والمدفوعات والمرتجعات والنزاعات والتحويلات والاشتراكات، وافهم مدة الإغلاق الحالية 14–60 يوماً.', heading: 'إغلاق eBay بعد إنهاء كل معاملة والتزامات البائع', overview: 'إغلاق حساب eBay يؤثر على الشراء والبيع والتقييم وسجل الحساب. المعاملات المفتوحة أو التزامات البائع قد تؤخر الإغلاق أو تمنعه.', points: ['تشترط eBay دفع الرسوم وتكاليف البيع ووصول الأموال المتاحة إلى صفر وإلغاء الاشتراكات وإنهاء العروض والمدفوعات والمرتجعات والنزاعات والتحويلات المعلقة.', 'توضح eBay حالياً أن الإغلاق يستغرق عادة 14 يوماً، وقد يصل إلى 60 يوماً إذا كانت هناك معاملات أو مدفوعات أو مطالبات أو نزاعات خلال آخر 30 يوماً.', 'خلال فترة الإغلاق يمكن عادة للحساب المؤهل والجيد طلب إلغاء الإغلاق. بعد الإغلاق النهائي لن يتوفر الوصول للشراء أو البيع ولا سجل التقييم والمشتريات والمبيعات.'] },
    fr: { title: 'Fermer définitivement eBay : transactions, fonds vendeur et données | Guide', description: 'Fermez eBay après avoir réglé enchères, paiements, retours, litiges, versements et abonnements, avec le délai actuel de 14 à 60 jours.', heading: 'Fermer eBay après avoir terminé toutes les transactions et obligations vendeur', overview: 'La fermeture eBay touche achats, ventes, évaluations et historique. Les transactions ouvertes ou obligations vendeur peuvent retarder ou bloquer la fermeture.', points: ['eBay exige de régler frais et coûts de vente, de ramener les fonds disponibles à zéro, d’annuler les abonnements et de résoudre enchères, paiements, retours, litiges et versements en attente.', 'eBay indique actuellement que la fermeture prend généralement 14 jours, mais peut aller jusqu’à 60 jours s’il y a eu transactions, paiements, réclamations ou litiges au cours des 30 derniers jours.', 'Pendant le délai, un compte éligible en règle peut généralement demander l’annulation de la fermeture. Après fermeture définitive, achats, ventes, évaluations et historiques ne sont plus accessibles.'] },
    tr: { title: 'eBay Hesabını Kalıcı Kapatma: Bekleyen İşlemler, Satıcı Bakiyesi ve Veriler', description: 'eBay hesabını kapatmadan önce teklif, ödeme, iade, anlaşmazlık, ödeme aktarımı ve abonelikleri çözün; 14–60 günlük süreci öğrenin.', heading: 'Tüm işlemler ve satıcı yükümlülükleri bittikten sonra eBay hesabını kapatın', overview: 'eBay hesabını kapatmak satın alma, satış, geri bildirim ve hesap geçmişini etkiler. Açık işlemler veya satıcı yükümlülükleri kapanışı geciktirebilir ya da engelleyebilir.', points: ['eBay; ücret ve satış maliyetlerinin ödenmesini, kullanılabilir bakiyenin sıfır olmasını, aboneliklerin iptalini ve açık teklif, ödeme, iade, anlaşmazlık ve aktarım işlemlerinin çözülmesini ister.', 'eBay şu anda hesabın genellikle 14 günde kapandığını, son 30 günde işlem, ödeme, talep veya anlaşmazlık varsa sürenin 60 güne çıkabileceğini belirtir.', 'Kapanış süresi içinde uygun ve iyi durumdaki bir hesap genellikle kapatma talebini iptal ettirebilir. Nihai kapanıştan sonra satın alma, satış, geri bildirim ve işlem geçmişine erişim kalmaz.'] }
  }
};

const TOPIC_PAGES_BATCH3 = {
  'deactivate-vs-delete-social-accounts': {
    kind: 'ids', value: ['twitter', 'facebook', 'instagram', 'linkedin', 'pinterest', 'snapchat', 'tiktok'],
    en: { title: 'Deactivate vs Delete Social Media Accounts Permanently | Guide', description: 'Compare temporary deactivation, hibernation and permanent deletion across major social platforms before you remove an account.', heading: 'Deactivate, hibernate or permanently delete a social account?', lead: 'Social platforms use different names and recovery windows for reversible and permanent actions. This hub helps you choose the correct control instead of deleting more than intended.', sections: [['Reversible options come first', 'Deactivation or hibernation can hide a profile while preserving a path back. Permanent deletion often starts a time-limited recovery window and then removes access.'], ['Check what survives account deletion', 'Messages, shared posts, search-engine caches and content copied by others can outlive the profile. Review the service guide before assuming account deletion erases every copy.']] },
    ar: { title: 'تعطيل أم حذف حساب التواصل نهائياً؟ | دليل', description: 'قارن بين التعطيل المؤقت والإسبات والحذف النهائي في شبكات التواصل قبل إزالة الحساب.', heading: 'تعطيل أو إسبات أم حذف حساب التواصل نهائياً؟', lead: 'تستخدم المنصات أسماء وفترات استعادة مختلفة للإجراءات المؤقتة والنهائية. استخدم هذه الصفحة لاختيار الإجراء الصحيح بدون حذف أكثر مما تريد.', sections: [['ابدأ بالخيار القابل للرجوع', 'التعطيل أو الإسبات يمكن أن يخفي الملف مع إبقاء إمكانية العودة. الحذف النهائي غالباً يبدأ بفترة استعادة محدودة ثم يزيل الوصول.'], ['راجع ما قد يبقى بعد الحذف', 'قد تبقى الرسائل والمنشورات المشتركة ونسخ محركات البحث والمحتوى المنسوخ لدى الآخرين بعد إزالة الملف، لذلك راجع دليل الخدمة أولاً.']] },
    fr: { title: 'Désactiver ou supprimer définitivement un réseau social | Guide', description: 'Comparez désactivation, mise en veille et suppression définitive sur les principales plateformes sociales.', heading: 'Désactiver, mettre en veille ou supprimer définitivement un compte social ?', lead: 'Les plateformes utilisent des noms et délais de récupération différents. Ce hub aide à choisir la bonne action sans supprimer davantage que prévu.', sections: [['Commencez par l’option réversible', 'La désactivation ou la mise en veille peut masquer le profil tout en permettant un retour. La suppression définitive comporte souvent une courte période de récupération.'], ['Vérifiez ce qui peut rester', 'Messages, contenus partagés, caches des moteurs et copies détenues par d’autres peuvent survivre au profil. Consultez le guide du service avant suppression.']] },
    tr: { title: 'Sosyal Medya Hesabını Devre Dışı Bırakma veya Kalıcı Silme | Rehber', description: 'Büyük sosyal platformlarda geçici kapatma, hazırda bekletme ve kalıcı silme seçeneklerini karşılaştırın.', heading: 'Sosyal hesabı devre dışı bırakmak, bekletmek veya kalıcı silmek mi?', lead: 'Platformlar geri dönüşlü ve kalıcı işlemler için farklı adlar ve kurtarma süreleri kullanır. Gereğinden fazlasını silmeden doğru işlemi seçin.', sections: [['Önce geri dönüşlü seçeneği düşünün', 'Devre dışı bırakma veya bekletme profili gizleyip geri dönüş yolu bırakabilir. Kalıcı silme ise çoğu zaman sınırlı bir kurtarma dönemiyle başlar.'], ['Silme sonrası kalabilecekleri kontrol edin', 'Mesajlar, paylaşılan gönderiler, arama motoru önbellekleri ve başkalarının kopyaları profil silindikten sonra kalabilir.']] }
  },
  'delete-work-and-cloud-accounts': {
    kind: 'ids', value: ['linkedin', 'slack', 'zoom', 'adobe', 'dropbox', 'github', 'microsoft'],
    en: { title: 'Delete Work & Cloud Accounts Without Losing Files or Ownership | Guide', description: 'Close work and cloud accounts after protecting files, repositories, workspace ownership, subscriptions and organization roles.', heading: 'Delete work and cloud accounts without abandoning data or ownership', lead: 'Work accounts can own files, repositories, workspaces, billing and organization roles. Resolve those dependencies before deleting the identity behind them.', sections: [['Transfer ownership before deletion', 'Check repositories, workspaces, teams and administrator roles. Transfer ownership where the provider requires it before closing the account.'], ['Back up cloud data and billing records', 'Download files and records you need and resolve paid subscriptions before deletion. Some services block deletion while an active plan or ownership obligation remains.']] },
    ar: { title: 'حذف حسابات العمل والسحابة بدون خسارة الملفات أو الملكية | دليل', description: 'أغلق حسابات العمل والسحابة بعد حماية الملفات والمستودعات وملكية المساحات والاشتراكات وأدوار الإدارة.', heading: 'حذف حسابات العمل والسحابة بدون ترك بيانات أو ملكية معلقة', lead: 'حسابات العمل قد تملك ملفات ومستودعات ومساحات وفوترة وأدوار إدارة. عالج هذه التبعيات قبل حذف الهوية التي تقف خلفها.', sections: [['انقل الملكية قبل الحذف', 'راجع المستودعات ومساحات العمل والفرق وأدوار الإدارة وانقل الملكية عندما تشترط الخدمة ذلك.'], ['انسخ بيانات السحابة وسجلات الفوترة', 'نزّل الملفات والسجلات التي تحتاجها وعالج الاشتراكات المدفوعة. بعض الخدمات تمنع الحذف بوجود خطة أو مسؤولية ملكية نشطة.']] },
    fr: { title: 'Supprimer des comptes de travail et cloud sans perdre fichiers ni propriété | Guide', description: 'Fermez les comptes professionnels et cloud après avoir protégé fichiers, dépôts, propriétés, abonnements et rôles administrateur.', heading: 'Supprimer les comptes de travail et cloud sans abandonner données ou propriété', lead: 'Les comptes professionnels peuvent posséder fichiers, dépôts, espaces, facturation et rôles administrateur. Réglez ces dépendances avant de supprimer l’identité.', sections: [['Transférez la propriété avant suppression', 'Vérifiez dépôts, espaces de travail, équipes et rôles administrateur. Transférez la propriété lorsque le fournisseur l’exige.'], ['Sauvegardez données cloud et facturation', 'Téléchargez fichiers et justificatifs nécessaires et réglez les abonnements payants. Certains services bloquent la suppression tant qu’une obligation reste active.']] },
    tr: { title: 'İş ve Bulut Hesaplarını Dosya veya Sahiplik Kaybetmeden Silme | Rehber', description: 'İş ve bulut hesaplarını dosya, depo, çalışma alanı sahipliği, abonelik ve yönetici rollerini güvenceye aldıktan sonra kapatın.', heading: 'Veri veya sahiplik bırakmadan iş ve bulut hesaplarını silin', lead: 'İş hesapları dosya, depo, çalışma alanı, faturalandırma ve yönetici rollerine sahip olabilir. Kimliği silmeden önce bu bağımlılıkları çözün.', sections: [['Silmeden önce sahipliği aktarın', 'Depoları, çalışma alanlarını, ekipleri ve yönetici rollerini kontrol edin. Sağlayıcı gerektiriyorsa sahipliği önce devredin.'], ['Bulut verilerini ve fatura kayıtlarını yedekleyin', 'Gerekli dosya ve kayıtları indirin, ücretli abonelikleri çözün. Bazı hizmetler aktif plan veya sahiplik sorumluluğu varken silmeyi engeller.']] }
  },
  'delete-payment-and-marketplace-accounts': {
    kind: 'ids', value: ['paypal', 'ebay', 'amazon'],
    en: { title: 'Delete Payment & Marketplace Accounts Safely | Balance, Orders & Disputes Guide', description: 'Close PayPal, eBay and Amazon accounts only after clearing balances, orders, disputes, refunds, payouts and retained records.', heading: 'Close payment and marketplace accounts after the money is settled', lead: 'Financial and marketplace accounts can have balances, refunds, disputes, seller payouts and legal retention requirements. Resolve them before requesting deletion.', sections: [['Clear balances and pending transactions', 'Transfer eligible balances, finish refunds, payouts, disputes and open orders, and cancel subscriptions before closure.'], ['Expect some legal retention', 'Financial providers and marketplaces may retain limited records after closure when law, fraud prevention, tax or dispute obligations require it.']] },
    ar: { title: 'حذف حسابات الدفع والمتاجر بأمان | دليل الرصيد والطلبات والنزاعات', description: 'أغلق PayPal وeBay وAmazon بعد تصفية الأرصدة والطلبات والنزاعات والاستردادات والتحويلات والسجلات المطلوبة.', heading: 'إغلاق حسابات الدفع والمتاجر بعد تسوية الأموال', lead: 'قد تحتوي هذه الحسابات على أرصدة واستردادات ونزاعات وتحويلات للبائع ومتطلبات احتفاظ قانونية. عالجها قبل طلب الحذف.', sections: [['صفِّ الرصيد والمعاملات المعلقة', 'انقل الأرصدة المؤهلة وأنهِ الاستردادات والتحويلات والنزاعات والطلبات المفتوحة وألغِ الاشتراكات قبل الإغلاق.'], ['توقع احتفاظاً قانونياً محدوداً', 'قد تحتفظ الجهات المالية والمتاجر بسجلات محدودة بعد الإغلاق عندما يفرض القانون أو منع الاحتيال أو الضرائب أو النزاعات ذلك.']] },
    fr: { title: 'Supprimer des comptes de paiement et marketplace en sécurité | Guide', description: 'Fermez PayPal, eBay et Amazon après avoir réglé soldes, commandes, litiges, remboursements, versements et obligations de conservation.', heading: 'Fermer les comptes de paiement et marketplace après règlement de l’argent', lead: 'Ces comptes peuvent avoir soldes, remboursements, litiges, versements vendeur et obligations légales. Réglez-les avant la suppression.', sections: [['Réglez soldes et transactions en attente', 'Transférez les soldes éligibles, terminez remboursements, versements, litiges et commandes puis annulez les abonnements.'], ['Prévoyez une conservation légale limitée', 'Les fournisseurs financiers et marketplaces peuvent conserver certains dossiers pour obligations légales, fiscales, antifraude ou de litige.']] },
    tr: { title: 'Ödeme ve Pazaryeri Hesaplarını Güvenle Silme | Bakiye ve İşlem Rehberi', description: 'PayPal, eBay ve Amazon hesaplarını bakiye, sipariş, uyuşmazlık, iade, ödeme aktarımı ve saklama yükümlülüklerini çözdükten sonra kapatın.', heading: 'Para işlemleri bittikten sonra ödeme ve pazaryeri hesaplarını kapatın', lead: 'Bu hesaplarda bakiye, iade, uyuşmazlık, satıcı ödemesi ve yasal saklama gereksinimleri olabilir. Silme talebinden önce bunları çözün.', sections: [['Bakiyeleri ve bekleyen işlemleri temizleyin', 'Uygun bakiyeleri aktarın, iade, ödeme, uyuşmazlık ve açık siparişleri tamamlayın, abonelikleri iptal edin.'], ['Sınırlı yasal saklama bekleyin', 'Finans ve pazaryeri sağlayıcıları yasa, dolandırıcılık önleme, vergi veya uyuşmazlık gereksinimleri nedeniyle bazı kayıtları kapatma sonrasında tutabilir.']] }
  },
  'cancel-streaming-before-deleting': {
    kind: 'ids', value: ['netflix', 'spotify'],
    en: { title: 'Cancel Streaming Subscription vs Delete Account | Netflix & Spotify Guide', description: 'Stop billing without deleting more than intended by separating streaming subscription cancellation from permanent account deletion.', heading: 'Cancel the subscription first when you only want billing to stop', lead: 'Streaming services separate billing from account identity. Canceling a plan can stop future charges without deleting profiles, history or the account itself.', sections: [['Canceling and deleting solve different problems', 'Use subscription cancellation when the goal is to stop charges. Use account deletion only when you also want the identity and eligible account data removed.'], ['Check the original billing provider', 'If a plan was purchased through an app store, carrier or partner, cancellation may need to happen with that provider rather than inside the streaming service.']] },
    ar: { title: 'إلغاء اشتراك البث أم حذف الحساب؟ دليل Netflix وSpotify', description: 'أوقف الفوترة بدون حذف أكثر مما تريد عبر التفريق بين إلغاء الاشتراك وحذف الحساب النهائي.', heading: 'ألغِ الاشتراك أولاً عندما يكون هدفك فقط إيقاف الفوترة', lead: 'تفصل خدمات البث بين الفوترة وهوية الحساب. إلغاء الخطة قد يوقف الرسوم بدون حذف الملفات أو السجل أو الحساب نفسه.', sections: [['الإلغاء والحذف يحلان مشكلتين مختلفتين', 'استخدم إلغاء الاشتراك لإيقاف الرسوم، واستخدم حذف الحساب فقط عندما تريد أيضاً إزالة الهوية وبيانات الحساب المؤهلة.'], ['راجع جهة الفوترة الأصلية', 'إذا اشتريت الخطة عبر متجر تطبيقات أو شركة اتصالات أو شريك فقد تحتاج للإلغاء من تلك الجهة بدلاً من داخل خدمة البث.']] },
    fr: { title: 'Résilier le streaming ou supprimer le compte ? Guide Netflix et Spotify', description: 'Arrêtez la facturation sans supprimer davantage que prévu en séparant résiliation de l’abonnement et suppression définitive du compte.', heading: 'Résiliez l’abonnement d’abord si votre objectif est seulement d’arrêter la facturation', lead: 'Les services de streaming séparent facturation et identité du compte. Résilier peut arrêter les frais sans supprimer profils, historique ou compte.', sections: [['Résiliation et suppression répondent à deux objectifs', 'Utilisez la résiliation pour stopper les frais. Supprimez le compte uniquement si vous souhaitez aussi retirer l’identité et les données éligibles.'], ['Vérifiez le fournisseur de facturation', 'Si le plan a été acheté via un store, opérateur ou partenaire, la résiliation peut devoir être faite auprès de ce fournisseur.']] },
    tr: { title: 'Yayın Aboneliğini İptal Etme veya Hesabı Silme | Netflix ve Spotify Rehberi', description: 'Yayın aboneliği iptali ile kalıcı hesap silmeyi ayırarak yalnızca faturalandırmayı durdurmak istediğinizde gereğinden fazlasını silmeyin.', heading: 'Amacınız yalnızca faturayı durdurmaksa önce aboneliği iptal edin', lead: 'Yayın hizmetleri faturalandırmayı hesap kimliğinden ayrı tutar. Plan iptali profil, geçmiş veya hesabı silmeden gelecekteki ücretleri durdurabilir.', sections: [['İptal ve silme farklı sorunları çözer', 'Ücretleri durdurmak için abonelik iptalini kullanın. Kimlik ve uygun hesap verilerini de kaldırmak istiyorsanız hesap silmeyi seçin.'], ['Asıl faturalandırma sağlayıcısını kontrol edin', 'Plan uygulama mağazası, operatör veya partner üzerinden alındıysa iptalin yayın hizmeti yerine o sağlayıcıdan yapılması gerekebilir.']] }
  }
};

module.exports = { GUIDE_CONTENT_BATCH3, TOPIC_PAGES_BATCH3 };
