const REVIEWED = '2026-08-22';

const GUIDE_CONTENT_BATCH2 = {
  facebook: {
    reviewed: REVIEWED,
    en: { title: 'Delete Facebook Permanently vs Deactivate: Download Data First | Guide', description: 'Delete Facebook permanently or deactivate it temporarily, download your information first, and understand what can remain visible after account removal.', heading: 'Delete Facebook permanently without confusing deletion with deactivation', overview: 'Facebook offers temporary deactivation and permanent deletion as separate actions. Use deactivation for a reversible break and deletion only when you are ready to remove the account and its profiles.', points: ['Meta says a Facebook deletion request can be cancelled by logging back in during the cancellation window; after the window ends, the account cannot be recovered.', 'Messages you sent can remain visible to recipients even after the account is deleted, so account deletion is not the same as erasing every copy of a conversation.', 'Download your Facebook information before deletion, and review Pages, additional profiles, Facebook Login connections and Meta Quest data that may depend on the account.'] },
    ar: { title: 'حذف Facebook نهائياً أم تعطيله؟ نزّل بياناتك أولاً | دليل', description: 'اختر بين حذف Facebook نهائياً أو تعطيله مؤقتاً، ونزّل معلوماتك وافهم ما الذي قد يبقى ظاهراً بعد إزالة الحساب.', heading: 'حذف Facebook نهائياً بدون الخلط بين الحذف والتعطيل', overview: 'يوفر Facebook التعطيل المؤقت والحذف النهائي كإجرائين مختلفين. استخدم التعطيل لاستراحة قابلة للرجوع، والحذف فقط عندما تكون مستعداً لإزالة الحساب وملفاته.', points: ['توضح Meta أن طلب حذف Facebook يمكن إلغاؤه بتسجيل الدخول ضمن نافذة الإلغاء، وبعد انتهائها لا يمكن استعادة الحساب.', 'قد تبقى الرسائل التي أرسلتها ظاهرة لدى المستلمين حتى بعد حذف الحساب، لذلك حذف الحساب لا يعني محو كل نسخة من المحادثات.', 'نزّل معلومات Facebook قبل الحذف وراجع الصفحات والملفات الإضافية وتسجيل الدخول عبر Facebook وبيانات Meta Quest التي قد تعتمد على الحساب.'] },
    fr: { title: 'Supprimer Facebook définitivement ou le désactiver : exportez vos données | Guide', description: 'Choisissez entre suppression définitive et désactivation temporaire de Facebook, téléchargez vos informations et vérifiez ce qui peut rester visible.', heading: 'Supprimer Facebook sans confondre suppression et désactivation', overview: 'Facebook distingue la désactivation temporaire de la suppression définitive. Utilisez la désactivation pour une pause réversible et la suppression lorsque vous souhaitez réellement fermer le compte.', points: ['Meta indique qu’une demande de suppression peut être annulée en se reconnectant pendant la fenêtre prévue ; après cette période, le compte ne peut plus être récupéré.', 'Les messages déjà envoyés peuvent rester visibles chez leurs destinataires, donc supprimer le compte ne supprime pas nécessairement toutes les copies d’une conversation.', 'Téléchargez vos informations avant la suppression et vérifiez Pages, profils supplémentaires, connexions Facebook Login et données Meta Quest liées au compte.'] },
    tr: { title: 'Facebook Hesabını Kalıcı Silme veya Devre Dışı Bırakma: Önce Verileri İndirin | Rehber', description: 'Facebook hesabını kalıcı silme ile geçici devre dışı bırakma arasındaki farkı öğrenin, verilerinizi indirin ve silme sonrası kalabilecek içerikleri kontrol edin.', heading: 'Facebook hesabını devre dışı bırakmayla karıştırmadan kalıcı olarak silin', overview: 'Facebook geçici devre dışı bırakma ile kalıcı silmeyi ayrı işlemler olarak sunar. Geri dönebileceğiniz bir ara için devre dışı bırakmayı, hesabı kapatmaya hazırsanız silmeyi kullanın.', points: ['Meta, silme isteğinin belirli iptal süresi içinde tekrar giriş yapılarak iptal edilebildiğini; bu süre sonrasında hesabın geri alınamadığını belirtir.', 'Gönderdiğiniz mesajlar alıcıların tarafında görünmeye devam edebilir; hesabı silmek her konuşma kopyasını silmekle aynı değildir.', 'Silmeden önce Facebook bilgilerinizi indirin ve hesaba bağlı Sayfaları, ek profilleri, Facebook Login bağlantılarını ve Meta Quest verilerini gözden geçirin.'] }
  },
  whatsapp: {
    reviewed: REVIEWED,
    en: { title: 'Delete a WhatsApp Account Safely: Chats, Backups & Linked Devices | Guide', description: 'Delete WhatsApp safely, distinguish account deletion from uninstalling the app, and review chats, backups, groups and linked devices first.', heading: 'Delete a WhatsApp account instead of only uninstalling the app', overview: 'Removing WhatsApp from a phone is not the same as deleting the WhatsApp account. Before using the account-deletion control, decide what chats, media and backup data you want to keep.', points: ['Use WhatsApp’s account-deletion control when you want to remove the account itself; uninstalling the application alone does not perform the same account action.', 'Export important chats or media you need to keep and review cloud backups separately, because local chat history, exports and backups are different data copies.', 'Check linked devices, important groups and your phone-number plan before deletion, especially if you are changing numbers rather than leaving WhatsApp completely.'] },
    ar: { title: 'حذف حساب WhatsApp بأمان: المحادثات والنسخ الاحتياطية والأجهزة | دليل', description: 'احذف حساب WhatsApp فعلياً بدل حذف التطبيق فقط، وراجع المحادثات والنسخ الاحتياطية والمجموعات والأجهزة المرتبطة أولاً.', heading: 'حذف حساب WhatsApp وليس مجرد إزالة التطبيق', overview: 'إزالة WhatsApp من الهاتف لا تعني حذف الحساب. قبل استخدام خيار حذف الحساب، قرر أي محادثات ووسائط ونسخ احتياطية تريد الاحتفاظ بها.', points: ['استخدم خيار حذف الحساب داخل WhatsApp عندما تريد إزالة الحساب نفسه؛ حذف التطبيق من الهاتف وحده ليس نفس الإجراء.', 'صدّر المحادثات أو الوسائط المهمة وراجع النسخ السحابية بشكل منفصل، لأن سجل الهاتف والتصدير والنسخة الاحتياطية نسخ مختلفة من البيانات.', 'راجع الأجهزة المرتبطة والمجموعات المهمة وخطة رقم الهاتف قبل الحذف، خصوصاً إذا كنت تغيّر الرقم بدلاً من مغادرة WhatsApp نهائياً.'] },
    fr: { title: 'Supprimer un compte WhatsApp : chats, sauvegardes et appareils liés | Guide', description: 'Supprimez réellement le compte WhatsApp au lieu de désinstaller seulement l’application et vérifiez chats, sauvegardes, groupes et appareils liés.', heading: 'Supprimer le compte WhatsApp, pas seulement l’application', overview: 'Désinstaller WhatsApp du téléphone ne supprime pas le compte. Avant d’utiliser la suppression du compte, décidez quelles conversations, pièces jointes et sauvegardes vous souhaitez conserver.', points: ['Utilisez le contrôle de suppression du compte WhatsApp pour retirer le compte lui-même ; désinstaller simplement l’application n’effectue pas la même action.', 'Exportez les chats ou médias importants et vérifiez séparément les sauvegardes cloud, car historique local, export et sauvegarde sont des copies distinctes.', 'Vérifiez les appareils liés, groupes importants et votre numéro de téléphone avant suppression, surtout si vous changez simplement de numéro.'] },
    tr: { title: 'WhatsApp Hesabını Güvenle Silme: Sohbetler, Yedekler ve Bağlı Cihazlar | Rehber', description: 'Yalnızca uygulamayı kaldırmak yerine WhatsApp hesabını silin; sohbetleri, yedekleri, grupları ve bağlı cihazları önce kontrol edin.', heading: 'WhatsApp uygulamasını kaldırmak yerine hesabı silin', overview: 'WhatsApp’ı telefondan kaldırmak hesabı silmez. Hesap silme kontrolünü kullanmadan önce hangi sohbet, medya ve yedek verilerini saklamak istediğinize karar verin.', points: ['Hesabın kendisini kaldırmak için WhatsApp’ın hesap silme kontrolünü kullanın; uygulamayı kaldırmak aynı hesap işlemi değildir.', 'Saklamak istediğiniz önemli sohbetleri veya medyayı dışa aktarın ve bulut yedeklerini ayrıca kontrol edin; yerel geçmiş, dışa aktarma ve yedek farklı veri kopyalarıdır.', 'Özellikle WhatsApp’tan tamamen ayrılmak yerine numara değiştiriyorsanız bağlı cihazları, önemli grupları ve telefon numarası planınızı gözden geçirin.'] }
  },
  discord: {
    reviewed: REVIEWED,
    en: { title: 'Delete Discord Account: Servers, Nitro, Messages & Data Package | Guide', description: 'Delete Discord safely, transfer server ownership, request your data first, understand the 15-day deletion process and distinguish deletion from disabling.', heading: 'Delete Discord after protecting servers and data you still need', overview: 'Discord provides both temporary account disabling and permanent deletion. Permanent deletion affects access, subscriptions and server ownership, so prepare those dependencies before starting.', points: ['Discord says account deletion takes 15 days to process and can be cancelled by restoring the account before permanent deletion completes.', 'You must transfer ownership of every server you own or delete those servers before Discord allows the account-deletion flow to finish.', 'Request and receive your Discord Data Package before deleting or disabling the account; Discord states that deleting or disabling before the download arrives cancels the data request.'] },
    ar: { title: 'حذف حساب Discord: السيرفرات وNitro والرسائل وحزمة البيانات | دليل', description: 'احذف Discord بأمان بعد نقل ملكية السيرفرات وطلب بياناتك، وافهم مدة الحذف والفرق بين التعطيل والحذف النهائي.', heading: 'حذف Discord بعد حماية السيرفرات والبيانات المهمة', overview: 'يوفر Discord تعطيل الحساب مؤقتاً وحذفه نهائياً. الحذف النهائي يؤثر على الوصول والاشتراكات وملكية السيرفرات، لذلك عالج هذه الأمور أولاً.', points: ['توضح Discord أن حذف الحساب يحتاج 15 يوماً للمعالجة ويمكن إلغاؤه باستعادة الحساب قبل اكتمال الحذف النهائي.', 'يجب نقل ملكية كل سيرفر تملكه أو حذف السيرفر قبل أن يسمح Discord بإكمال حذف الحساب.', 'اطلب حزمة بيانات Discord واستلمها قبل حذف الحساب أو تعطيله؛ توضح Discord أن الحذف أو التعطيل قبل وصول رابط التنزيل يلغي طلب البيانات.'] },
    fr: { title: 'Supprimer Discord : serveurs, Nitro, messages et paquet de données | Guide', description: 'Supprimez Discord après avoir transféré les serveurs et demandé vos données, et comprenez le délai de suppression et la différence avec la désactivation.', heading: 'Supprimer Discord après avoir protégé serveurs et données utiles', overview: 'Discord propose la désactivation temporaire et la suppression définitive. La suppression touche l’accès, les abonnements et la propriété des serveurs ; préparez donc ces éléments avant de commencer.', points: ['Discord indique que la suppression prend 15 jours et peut être annulée en restaurant le compte avant la suppression définitive.', 'Vous devez transférer la propriété de tous les serveurs que vous possédez ou les supprimer avant de pouvoir terminer la suppression du compte.', 'Demandez et recevez votre paquet de données Discord avant suppression ou désactivation ; Discord précise que l’action annule une demande de données encore en attente.'] },
    tr: { title: 'Discord Hesabını Silme: Sunucular, Nitro, Mesajlar ve Veri Paketi | Rehber', description: 'Discord hesabını silmeden önce sunucu sahipliğini aktarın, veri paketinizi alın ve 15 günlük silme süreci ile devre dışı bırakma farkını öğrenin.', heading: 'Sunucuları ve gerekli verileri koruduktan sonra Discord hesabını silin', overview: 'Discord geçici devre dışı bırakma ve kalıcı hesap silme seçenekleri sunar. Kalıcı silme erişimi, abonelikleri ve sunucu sahipliğini etkileyebilir.', points: ['Discord, hesap silmenin 15 gün sürdüğünü ve kalıcı silme tamamlanmadan önce hesabı geri yükleyerek işlemin iptal edilebildiğini belirtir.', 'Hesap silme işlemini tamamlamadan önce sahip olduğunuz tüm sunucuların sahipliğini devretmeniz veya sunucuları silmeniz gerekir.', 'Discord Veri Paketinizi silme veya devre dışı bırakma işleminden önce isteyip indirin; Discord, bağlantı gelmeden hesabı silmenin veri talebini iptal ettiğini belirtir.'] }
  },
  telegram: {
    reviewed: REVIEWED,
    en: { title: 'Delete Telegram Permanently: Messages, Groups & Contacts | Guide', description: 'Delete Telegram permanently and understand what happens to messages, contacts, groups and channels before using the irreversible account-deletion page.', heading: 'Delete Telegram only after checking messages, groups and channels', overview: 'Telegram account deletion is irreversible and broader than deleting individual chats or clearing selected data. If you only want to remove specific content, use the narrower privacy controls first.', points: ['Telegram says deleting the account permanently removes messages and contacts associated with the account and cannot be undone.', 'Groups and channels created by the account are left without their creator, while existing administrators keep their rights.', 'Other people can still retain their copies of messages you previously sent, so delete specific chats or messages for both parties first when that is your actual goal.'] },
    ar: { title: 'حذف Telegram نهائياً: الرسائل والمجموعات وجهات الاتصال | دليل', description: 'احذف Telegram نهائياً بعد فهم ما يحدث للرسائل وجهات الاتصال والمجموعات والقنوات واستخدم الحذف المحدد إذا كان هدفك أضيق.', heading: 'حذف Telegram بعد مراجعة الرسائل والمجموعات والقنوات', overview: 'حذف حساب Telegram نهائي ولا يمكن التراجع عنه، وهو أوسع من حذف محادثات أو بيانات محددة. إذا كنت تريد إزالة محتوى معين فقط فاستخدم أدوات الخصوصية الأقل تدميراً.', points: ['توضح Telegram أن حذف الحساب يزيل الرسائل وجهات الاتصال المرتبطة بالحساب بشكل دائم ولا يمكن التراجع عن العملية.', 'المجموعات والقنوات التي أنشأها الحساب تبقى بدون منشئ، بينما يحتفظ المشرفون الحاليون بصلاحياتهم.', 'قد يحتفظ الآخرون بنسخ الرسائل التي أرسلتها سابقاً، لذلك احذف الرسائل أو المحادثات للطرفين أولاً إذا كان هذا هو هدفك الحقيقي.'] },
    fr: { title: 'Supprimer Telegram définitivement : messages, groupes et contacts | Guide', description: 'Supprimez Telegram après avoir compris les effets sur les messages, contacts, groupes et canaux et utilisez une suppression ciblée si nécessaire.', heading: 'Supprimer Telegram après avoir vérifié messages, groupes et canaux', overview: 'La suppression du compte Telegram est irréversible et plus large que la suppression de chats ou de données précises. Utilisez les contrôles plus ciblés si votre objectif est limité.', points: ['Telegram indique que la suppression du compte retire définitivement les messages et contacts associés au compte et ne peut pas être annulée.', 'Les groupes et canaux créés par le compte restent sans créateur, tandis que les administrateurs existants conservent leurs droits.', 'Les autres utilisateurs peuvent conserver leur copie de messages déjà reçus ; supprimez donc d’abord les messages ou chats pour les deux parties si c’est votre objectif.'] },
    tr: { title: 'Telegram Hesabını Kalıcı Silme: Mesajlar, Gruplar ve Kişiler | Rehber', description: 'Telegram hesabını silmeden önce mesaj, kişi, grup ve kanallara ne olacağını öğrenin; yalnızca içerik silmek istiyorsanız daha dar kontrolleri kullanın.', heading: 'Mesajları, grupları ve kanalları kontrol ettikten sonra Telegram hesabını silin', overview: 'Telegram hesabını silmek geri alınamaz ve tek tek sohbetleri veya belirli verileri silmekten daha kapsamlıdır. Daha dar bir hedefiniz varsa ilgili gizlilik kontrolünü kullanın.', points: ['Telegram, hesap silmenin hesaba bağlı mesajları ve kişileri kalıcı olarak kaldırdığını ve işlemin geri alınamayacağını belirtir.', 'Hesabın oluşturduğu grup ve kanallar yaratıcısız kalır; mevcut yöneticiler yetkilerini korur.', 'Daha önce gönderdiğiniz mesajların kopyaları diğer kişilerde kalabilir; amacınız buysa hesap silmeden önce sohbet veya mesajları iki taraf için silin.'] }
  },
  microsoft: {
    reviewed: REVIEWED,
    en: { title: 'Close Microsoft Account Safely: Outlook, OneDrive, Xbox & Subscriptions | Guide', description: 'Close a Microsoft account without losing Outlook, OneDrive, Xbox or purchased content unexpectedly; review data and the 30- or 60-day reopen window first.', heading: 'Close a Microsoft account after checking the services tied to it', overview: 'A Microsoft account can be the identity for Outlook.com, OneDrive, Xbox, Windows and other consumer services. Closing it is much broader than removing one app or email address.', points: ['Microsoft lets you choose a 30- or 60-day reopen window when marking an account for closure; after that window the account is permanently deleted.', 'Closing the Microsoft account can remove access to Outlook.com email and contacts, OneDrive, Xbox and other services tied to the same identity.', 'Review and export important files or service data, use remaining balances or purchases where appropriate, and check subscriptions before marking the account for closure.'] },
    ar: { title: 'إغلاق حساب Microsoft بأمان: Outlook وOneDrive وXbox والاشتراكات | دليل', description: 'أغلق حساب Microsoft بدون خسارة Outlook أو OneDrive أو Xbox بشكل مفاجئ، وراجع البيانات والاشتراكات ونافذة الاستعادة أولاً.', heading: 'إغلاق حساب Microsoft بعد مراجعة الخدمات المرتبطة به', overview: 'قد يكون حساب Microsoft هو الهوية المستخدمة في Outlook.com وOneDrive وXbox وWindows وخدمات أخرى. إغلاقه أوسع بكثير من إزالة تطبيق أو بريد واحد.', points: ['تسمح Microsoft باختيار نافذة إعادة فتح مدتها 30 أو 60 يوماً عند وضع الحساب للإغلاق، وبعد انتهاء النافذة يُحذف الحساب نهائياً.', 'إغلاق حساب Microsoft قد يزيل الوصول إلى بريد Outlook.com وجهات الاتصال وOneDrive وXbox وخدمات أخرى مرتبطة بنفس الهوية.', 'راجع الملفات والبيانات المهمة وصدّر ما تحتاجه، واستخدم الأرصدة أو المشتريات المناسبة، وتحقق من الاشتراكات قبل وضع الحساب للإغلاق.'] },
    fr: { title: 'Fermer un compte Microsoft : Outlook, OneDrive, Xbox et abonnements | Guide', description: 'Fermez un compte Microsoft sans perdre par surprise Outlook, OneDrive ou Xbox et vérifiez données, abonnements et fenêtre de réouverture.', heading: 'Fermer un compte Microsoft après avoir vérifié les services liés', overview: 'Un compte Microsoft peut servir d’identité à Outlook.com, OneDrive, Xbox, Windows et d’autres services. Le fermer est bien plus large que supprimer une application ou une adresse e-mail.', points: ['Microsoft permet de choisir une fenêtre de réouverture de 30 ou 60 jours lors de la fermeture ; après cette période, le compte est supprimé définitivement.', 'La fermeture peut retirer l’accès à Outlook.com, aux contacts, à OneDrive, à Xbox et à d’autres services liés à la même identité.', 'Exportez les fichiers et données importants, vérifiez les soldes ou achats utiles et contrôlez les abonnements avant de marquer le compte pour fermeture.'] },
    tr: { title: 'Microsoft Hesabını Güvenle Kapatma: Outlook, OneDrive, Xbox ve Abonelikler | Rehber', description: 'Microsoft hesabını kapatmadan önce Outlook, OneDrive, Xbox, satın alınan içerikler, abonelikler ve 30/60 günlük yeniden açma süresini kontrol edin.', heading: 'Bağlı hizmetleri kontrol ettikten sonra Microsoft hesabını kapatın', overview: 'Microsoft hesabı Outlook.com, OneDrive, Xbox, Windows ve diğer tüketici hizmetlerinin ortak kimliği olabilir. Hesabı kapatmak tek bir uygulamayı kaldırmaktan çok daha kapsamlıdır.', points: ['Microsoft, hesabı kapatırken 30 veya 60 günlük yeniden açma penceresi seçmenize izin verir; bu süre geçtikten sonra hesap kalıcı olarak silinir.', 'Microsoft hesabını kapatmak Outlook.com e-posta ve kişilerine, OneDrive’a, Xbox’a ve aynı kimliğe bağlı diğer hizmetlere erişimi sona erdirebilir.', 'Kapatma işleminden önce önemli dosya veya hizmet verilerini dışa aktarın, gerekli bakiye ve satın alımları kontrol edin ve abonelikleri gözden geçirin.'] }
  },
  apple: {
    reviewed: REVIEWED,
    en: { title: 'Delete an Apple Account: iCloud Data, Devices & Subscriptions | Guide', description: 'Delete an Apple Account through Apple privacy tools after backing up iCloud data and reviewing devices, subscriptions and Sign in with Apple connections.', heading: 'Delete an Apple Account only after backing up the Apple ecosystem', overview: 'An Apple Account can connect iCloud data, devices, purchases, subscriptions and Sign in with Apple relationships. Permanent deletion is therefore an ecosystem-level action, not an app-level cleanup.', points: ['Apple provides a Data and Privacy portal where users can request a copy of account data, temporarily deactivate an Apple Account or permanently delete it.', 'Back up or transfer iCloud Photos, files and other data you need before deletion because the Apple Account is the identity used to access iCloud and other Apple services.', 'Review active subscriptions, trusted devices and Sign in with Apple relationships before deletion so you do not unexpectedly lose an access path you still need.'] },
    ar: { title: 'حذف حساب Apple: بيانات iCloud والأجهزة والاشتراكات | دليل', description: 'احذف حساب Apple عبر أدوات الخصوصية بعد نسخ بيانات iCloud ومراجعة الأجهزة والاشتراكات وتسجيل الدخول باستخدام Apple.', heading: 'حذف حساب Apple بعد أخذ نسخة من بيانات منظومة Apple', overview: 'يربط حساب Apple بين iCloud والأجهزة والمشتريات والاشتراكات وخدمات تسجيل الدخول. لذلك الحذف النهائي إجراء على مستوى المنظومة وليس مجرد تنظيف تطبيق واحد.', points: ['توفر Apple بوابة البيانات والخصوصية لطلب نسخة من البيانات أو تعطيل حساب Apple مؤقتاً أو حذفه نهائياً.', 'انسخ أو انقل صور iCloud والملفات والبيانات التي تحتاجها قبل الحذف لأن حساب Apple هو الهوية المستخدمة للوصول إلى iCloud وخدمات Apple الأخرى.', 'راجع الاشتراكات النشطة والأجهزة الموثوقة وعلاقات تسجيل الدخول باستخدام Apple قبل الحذف حتى لا تفقد وسيلة وصول ما زلت تحتاجها.'] },
    fr: { title: 'Supprimer un compte Apple : données iCloud, appareils et abonnements | Guide', description: 'Supprimez un compte Apple via les outils de confidentialité après avoir sauvegardé iCloud et vérifié appareils, abonnements et Sign in with Apple.', heading: 'Supprimer un compte Apple après avoir sauvegardé l’écosystème Apple', overview: 'Le compte Apple relie iCloud, appareils, achats, abonnements et connexions Sign in with Apple. Sa suppression définitive concerne donc tout l’écosystème.', points: ['Apple fournit un portail Données et confidentialité permettant de demander une copie des données, de désactiver temporairement ou de supprimer définitivement le compte Apple.', 'Sauvegardez ou transférez Photos iCloud, fichiers et autres données nécessaires, car le compte Apple sert d’identité pour iCloud et d’autres services Apple.', 'Vérifiez abonnements actifs, appareils de confiance et connexions Sign in with Apple afin de ne pas perdre un moyen d’accès encore nécessaire.'] },
    tr: { title: 'Apple Hesabını Silme: iCloud Verileri, Cihazlar ve Abonelikler | Rehber', description: 'Apple Hesabını silmeden önce iCloud verilerini yedekleyin ve cihazları, abonelikleri ve Apple ile Giriş bağlantılarını kontrol edin.', heading: 'Apple ekosistemini yedekledikten sonra Apple Hesabını silin', overview: 'Apple Hesabı iCloud verileri, cihazlar, satın alımlar, abonelikler ve Apple ile Giriş ilişkilerini birbirine bağlayabilir. Kalıcı silme tüm ekosistemi etkileyebilir.', points: ['Apple’ın Veri ve Gizlilik portalı hesap verilerinin kopyasını isteme, Apple Hesabını geçici olarak devre dışı bırakma ve kalıcı olarak silme araçları sunar.', 'Apple Hesabı iCloud ve diğer Apple hizmetlerine erişimde kullanıldığı için silmeden önce gerekli iCloud Fotoğrafları, dosyaları ve diğer verileri yedekleyin veya aktarın.', 'Hâlâ gereken bir erişim yöntemini kaybetmemek için aktif abonelikleri, güvenilir cihazları ve Apple ile Giriş bağlantılarını gözden geçirin.'] }
  },
  snapchat: {
    reviewed: REVIEWED,
    en: { title: 'Delete Snapchat Account: 30-Day Deactivation, Memories & Data | Guide', description: 'Delete Snapchat safely, understand the initial 30-day deactivation period, download Memories and account data, and know when recovery stops being possible.', heading: 'Delete Snapchat after downloading Memories and account data', overview: 'Snapchat starts account deletion with a deactivation period. Use that time to make sure you have downloaded Memories and other data you need and understand when the account becomes unrecoverable.', points: ['Snapchat says deletion first deactivates the account for 30 days, during which it can be reactivated by logging back in.', 'After the initial period the account is no longer recoverable and the deletion process continues; some data can still be retained for legal, security or business needs.', 'Use Snapchat My Data before or during the available download period to export account information and Memories you want to keep.'] },
    ar: { title: 'حذف حساب Snapchat: التعطيل 30 يوماً والذكريات والبيانات | دليل', description: 'احذف Snapchat بأمان وافهم فترة التعطيل الأولى ومدتها 30 يوماً، ونزّل Memories وبيانات الحساب قبل فقدان إمكانية الاسترداد.', heading: 'حذف Snapchat بعد تنزيل Memories وبيانات الحساب', overview: 'يبدأ Snapchat حذف الحساب بفترة تعطيل. استغل هذه الفترة للتأكد من تنزيل Memories والبيانات المهمة وفهم متى يتوقف الاسترداد.', points: ['توضح Snapchat أن الحذف يبدأ بتعطيل الحساب لمدة 30 يوماً ويمكن خلال هذه الفترة إعادة تفعيله بتسجيل الدخول.', 'بعد الفترة الأولى لا يعود الحساب قابلاً للاسترداد وتستمر عملية الحذف، وقد تُحتفظ بعض البيانات لأسباب قانونية أو أمنية أو تجارية.', 'استخدم My Data في Snapchat قبل الحذف أو ضمن فترة التنزيل المتاحة لتصدير معلومات الحساب وMemories التي تريد الاحتفاظ بها.'] },
    fr: { title: 'Supprimer Snapchat : désactivation de 30 jours, Memories et données | Guide', description: 'Supprimez Snapchat en comprenant la première période de désactivation de 30 jours et téléchargez Memories et données avant la fin de la récupération.', heading: 'Supprimer Snapchat après avoir téléchargé Memories et données', overview: 'Snapchat commence la suppression par une période de désactivation. Utilisez-la pour télécharger Memories et les données importantes et comprendre quand la récupération devient impossible.', points: ['Snapchat indique que la suppression commence par 30 jours de désactivation pendant lesquels le compte peut être réactivé en se reconnectant.', 'Après cette première période, le compte n’est plus récupérable et la suppression se poursuit ; certaines données peuvent être conservées pour des raisons légales, de sécurité ou commerciales.', 'Utilisez My Data avant la suppression ou pendant la période de téléchargement disponible pour exporter les informations et Memories à conserver.'] },
    tr: { title: 'Snapchat Hesabını Silme: 30 Gün Devre Dışı, Memories ve Veriler | Rehber', description: 'Snapchat hesabını silerken ilk 30 günlük devre dışı dönemini anlayın ve geri dönüş imkânı bitmeden Memories ile hesap verilerini indirin.', heading: 'Memories ve hesap verilerini indirdikten sonra Snapchat hesabını silin', overview: 'Snapchat hesap silmeyi bir devre dışı bırakma dönemiyle başlatır. Bu zamanı Memories ve önemli verileri indirmek ve geri dönüş sınırını anlamak için kullanın.', points: ['Snapchat, hesap silmenin önce 30 günlük devre dışı dönemle başladığını ve bu sürede tekrar giriş yaparak hesabın etkinleştirilebildiğini belirtir.', 'İlk dönemden sonra hesap artık kurtarılamaz ve silme süreci devam eder; bazı veriler yasal, güvenlik veya iş gereksinimleri nedeniyle saklanabilir.', 'Saklamak istediğiniz hesap bilgileri ve Memories için silmeden önce veya mevcut indirme süresi içinde Snapchat My Data aracını kullanın.'] }
  },
  spotify: {
    reviewed: REVIEWED,
    en: { title: 'Delete Spotify Account vs Cancel Premium: Playlists, Purchases & Data | Guide', description: 'Understand the difference between deleting Spotify and cancelling Premium, then protect playlists, purchases and account data before permanent closure.', heading: 'Delete Spotify only if cancelling Premium is not enough', overview: 'Spotify account deletion is different from stopping a paid Premium plan. If you want to keep Spotify on the free tier, cancel Premium instead of closing the account.', points: ['Spotify says users who only want to stop paying can cancel Premium and continue with the free, ad-supported service instead of deleting the account.', 'After account closure, Spotify sends a reactivation link that can be used within 7 days; after that the account cannot be reactivated and data deletion begins.', 'Closing the account can remove access to purchased audiobooks or future-event tickets, so review purchases, playlists and any data you want to preserve first.'] },
    ar: { title: 'حذف Spotify أم إلغاء Premium؟ القوائم والمشتريات والبيانات | دليل', description: 'افهم الفرق بين حذف حساب Spotify وإلغاء Premium، وراجع القوائم والمشتريات والبيانات قبل الإغلاق النهائي.', heading: 'حذف Spotify فقط إذا كان إلغاء Premium غير كافٍ', overview: 'حذف حساب Spotify يختلف عن إيقاف خطة Premium المدفوعة. إذا كنت تريد الاستمرار بالخطة المجانية، ألغِ Premium بدلاً من حذف الحساب.', points: ['توضح Spotify أن من يريد إيقاف الدفع فقط يمكنه إلغاء Premium والاستمرار بالخدمة المجانية المدعومة بالإعلانات بدلاً من حذف الحساب.', 'بعد إغلاق الحساب ترسل Spotify رابط إعادة تفعيل يمكن استخدامه خلال 7 أيام؛ بعد ذلك لا يمكن إعادة تفعيل الحساب وتبدأ عملية حذف البيانات.', 'قد يؤدي إغلاق الحساب إلى فقدان الوصول إلى الكتب الصوتية المشتراة أو تذاكر فعاليات مستقبلية، لذلك راجع المشتريات والقوائم والبيانات أولاً.'] },
    fr: { title: 'Supprimer Spotify ou annuler Premium ? Playlists, achats et données | Guide', description: 'Comprenez la différence entre supprimer Spotify et annuler Premium, puis protégez playlists, achats et données avant la fermeture définitive.', heading: 'Supprimer Spotify seulement si annuler Premium ne suffit pas', overview: 'La suppression du compte Spotify est différente de l’arrêt d’un abonnement Premium. Pour continuer avec l’offre gratuite, annulez Premium sans fermer le compte.', points: ['Spotify indique que les utilisateurs souhaitant seulement arrêter de payer peuvent annuler Premium et continuer avec le service gratuit financé par la publicité.', 'Après fermeture, Spotify envoie un lien de réactivation utilisable pendant 7 jours ; ensuite le compte ne peut plus être réactivé et la suppression des données commence.', 'La fermeture peut faire perdre l’accès à des livres audio achetés ou à des billets pour des événements futurs ; vérifiez donc achats, playlists et données utiles.'] },
    tr: { title: 'Spotify Hesabını Silme mi Premium İptali mi? Listeler, Satın Alımlar ve Veriler | Rehber', description: 'Spotify hesabını silme ile Premium iptali arasındaki farkı öğrenin ve kalıcı kapatmadan önce çalma listelerini, satın alımları ve verileri koruyun.', heading: 'Premium iptali yeterli değilse Spotify hesabını silin', overview: 'Spotify hesabını silmek ücretli Premium planını durdurmaktan farklıdır. Spotify’ı ücretsiz planda kullanmaya devam etmek istiyorsanız hesabı kapatmak yerine Premium’u iptal edin.', points: ['Spotify, yalnızca ödeme yapmayı durdurmak isteyen kullanıcıların Premium’u iptal edip reklam destekli ücretsiz hizmette kalabileceğini belirtir.', 'Hesap kapatıldıktan sonra Spotify 7 gün içinde kullanılabilen bir yeniden etkinleştirme bağlantısı gönderir; sonrasında hesap yeniden açılamaz ve veri silme süreci başlar.', 'Hesabı kapatmak satın alınmış sesli kitaplara veya gelecekteki etkinlik biletlerine erişimi kaybettirebilir; satın alımları, listeleri ve gerekli verileri önce kontrol edin.'] }
  },
  steam: {
    reviewed: REVIEWED,
    en: { title: 'Delete a Steam Account Safely: Games, Wallet, Inventory & Proof of Ownership | Guide', description: 'Request Steam account deletion only after reviewing game licenses, Wallet funds, inventory and account ownership requirements.', heading: 'Delete a Steam account only after checking games and account value', overview: 'Steam accounts can contain game licenses, Wallet funds, inventory items, community history and security credentials. Treat deletion as a high-impact account action rather than routine profile cleanup.', points: ['Steam Support says account deletion is handled through a deletion request and may require comprehensive proof of account ownership before the request is fulfilled.', 'Steam accounts cannot be merged and game subscriptions or product keys are not transferable between accounts, so do not assume purchases can be moved to another Steam account.', 'Review your library, Wallet balance, inventory, market activity, Steam Guard and any data you need before submitting the deletion request.'] },
    ar: { title: 'حذف حساب Steam بأمان: الألعاب والمحفظة والمخزون وإثبات الملكية | دليل', description: 'اطلب حذف Steam فقط بعد مراجعة تراخيص الألعاب ورصيد المحفظة والمخزون ومتطلبات إثبات ملكية الحساب.', heading: 'حذف Steam بعد مراجعة الألعاب والقيمة المرتبطة بالحساب', overview: 'قد يحتوي حساب Steam على تراخيص ألعاب ورصيد Wallet ومخزون وسجل مجتمع وبيانات أمان. لذلك تعامل مع الحذف كإجراء عالي التأثير وليس تنظيفاً عادياً للملف.', points: ['توضح Steam Support أن حذف الحساب يتم عبر طلب حذف وقد يتطلب إثباتاً شاملاً لملكية الحساب قبل تنفيذ الطلب.', 'لا يمكن دمج حسابات Steam كما أن اشتراكات الألعاب أو مفاتيح المنتجات غير قابلة للنقل بين الحسابات، لذلك لا تفترض إمكانية نقل المشتريات إلى حساب آخر.', 'راجع مكتبة الألعاب ورصيد Wallet والمخزون ونشاط السوق وSteam Guard وأي بيانات تحتاجها قبل إرسال طلب الحذف.'] },
    fr: { title: 'Supprimer un compte Steam : jeux, portefeuille, inventaire et preuve de propriété | Guide', description: 'Demandez la suppression Steam seulement après avoir vérifié licences de jeux, fonds du portefeuille, inventaire et exigences de preuve de propriété.', heading: 'Supprimer Steam après avoir vérifié les jeux et la valeur du compte', overview: 'Un compte Steam peut contenir licences de jeux, fonds du portefeuille, objets d’inventaire, historique communautaire et informations de sécurité. La suppression est donc une action à fort impact.', points: ['Steam Support indique que la suppression passe par une demande et peut nécessiter une preuve complète de propriété du compte avant son exécution.', 'Les comptes Steam ne peuvent pas être fusionnés et les abonnements de jeux ou clés produit ne sont pas transférables entre comptes ; ne supposez donc pas pouvoir déplacer vos achats.', 'Vérifiez bibliothèque, solde du portefeuille, inventaire, activité du marché, Steam Guard et données nécessaires avant d’envoyer la demande.'] },
    tr: { title: 'Steam Hesabını Güvenle Silme: Oyunlar, Cüzdan, Envanter ve Sahiplik Kanıtı | Rehber', description: 'Steam hesabını silme talebinden önce oyun lisanslarını, Cüzdan bakiyesini, envanteri ve hesap sahipliği gereksinimlerini kontrol edin.', heading: 'Oyunları ve hesap değerini kontrol ettikten sonra Steam hesabını silin', overview: 'Steam hesabında oyun lisansları, Cüzdan bakiyesi, envanter öğeleri, topluluk geçmişi ve güvenlik bilgileri bulunabilir. Silme işlemi yüksek etkili bir hesap işlemidir.', points: ['Steam Support, hesap silmenin bir silme talebi üzerinden yürütüldüğünü ve işlemden önce kapsamlı sahiplik kanıtı istenebileceğini belirtir.', 'Steam hesapları birleştirilemez ve oyun abonelikleri ya da ürün anahtarları hesaplar arasında aktarılamaz; satın alımların başka hesaba taşınacağını varsaymayın.', 'Talebi göndermeden önce oyun kitaplığını, Cüzdan bakiyesini, envanteri, pazar etkinliğini, Steam Guard’ı ve gerekli verileri gözden geçirin.'] }
  },
  amazon: {
    reviewed: REVIEWED,
    en: { title: 'Close an Amazon Account Safely: Orders, Prime, Digital Purchases & Data | Guide', description: 'Close an Amazon account only after reviewing orders, refunds, Prime and other subscriptions, gift-card balances, digital purchases and account data.', heading: 'Close an Amazon account after clearing orders, subscriptions and balances', overview: 'Closing an Amazon account is broader than cancelling Prime or deleting a payment method. The account can be tied to orders, refunds, subscriptions, balances and digital services that should be reviewed first.', points: ['Do not use account closure merely to stop a subscription: review Prime and any other recurring services separately so billing changes match what you actually intend.', 'Check open orders, returns, refunds, gift-card balances and digital purchases before closure because you may still need the account to manage or document those transactions.', 'Request or save account records you need and review devices, payment methods and connected Amazon services before using the permanent account-closure flow.'] },
    ar: { title: 'إغلاق حساب Amazon بأمان: الطلبات وPrime والمشتريات والبيانات | دليل', description: 'أغلق Amazon فقط بعد مراجعة الطلبات والاستردادات وPrime والاشتراكات والأرصدة والمشتريات الرقمية والبيانات المهمة.', heading: 'إغلاق Amazon بعد إنهاء الطلبات والاشتراكات والأرصدة المهمة', overview: 'إغلاق حساب Amazon أوسع من إلغاء Prime أو إزالة وسيلة دفع. قد يرتبط الحساب بطلبات واستردادات واشتراكات وأرصدة وخدمات رقمية يجب مراجعتها أولاً.', points: ['لا تستخدم إغلاق الحساب فقط لإيقاف اشتراك؛ راجع Prime وأي خدمات متكررة بشكل منفصل حتى يطابق تغيير الفوترة ما تريده فعلاً.', 'تحقق من الطلبات المفتوحة والمرتجعات والاستردادات وأرصدة بطاقات الهدايا والمشتريات الرقمية لأنك قد تحتاج الحساب لإدارة هذه العمليات أو إثباتها.', 'احفظ سجلات الحساب التي تحتاجها وراجع الأجهزة ووسائل الدفع وخدمات Amazon المرتبطة قبل استخدام مسار الإغلاق النهائي.'] },
    fr: { title: 'Fermer un compte Amazon : commandes, Prime, achats numériques et données | Guide', description: 'Fermez Amazon seulement après avoir vérifié commandes, remboursements, Prime, abonnements, soldes, achats numériques et données utiles.', heading: 'Fermer Amazon après avoir réglé commandes, abonnements et soldes', overview: 'Fermer un compte Amazon est plus large qu’annuler Prime ou retirer une carte bancaire. Le compte peut être lié à des commandes, remboursements, abonnements, soldes et services numériques.', points: ['N’utilisez pas la fermeture du compte uniquement pour arrêter un abonnement ; vérifiez séparément Prime et les autres services récurrents afin que la facturation corresponde à votre intention.', 'Contrôlez commandes ouvertes, retours, remboursements, soldes de cartes-cadeaux et achats numériques car le compte peut encore être nécessaire pour gérer ou documenter ces opérations.', 'Enregistrez les données de compte utiles et vérifiez appareils, moyens de paiement et services Amazon liés avant d’utiliser la fermeture définitive.'] },
    tr: { title: 'Amazon Hesabını Güvenle Kapatma: Siparişler, Prime, Dijital Satın Alımlar ve Veriler | Rehber', description: 'Amazon hesabını kapatmadan önce siparişleri, iadeleri, Prime ve diğer abonelikleri, hediye kartı bakiyelerini, dijital satın alımları ve verileri kontrol edin.', heading: 'Siparişleri, abonelikleri ve bakiyeleri kontrol ettikten sonra Amazon hesabını kapatın', overview: 'Amazon hesabını kapatmak Prime’ı iptal etmekten veya ödeme yöntemini kaldırmaktan daha kapsamlıdır. Hesap sipariş, iade, abonelik, bakiye ve dijital hizmetlerle bağlantılı olabilir.', points: ['Yalnızca aboneliği durdurmak için hesabı kapatmayın; Prime ve diğer tekrarlayan hizmetleri ayrı kontrol ederek faturalandırma değişikliğinin amacınıza uygun olduğundan emin olun.', 'Açık siparişleri, iadeleri, geri ödemeleri, hediye kartı bakiyelerini ve dijital satın alımları kontrol edin; bu işlemleri yönetmek veya belgelemek için hesaba ihtiyaç duyabilirsiniz.', 'Kalıcı hesap kapatma akışını kullanmadan önce gerekli hesap kayıtlarını kaydedin ve cihazları, ödeme yöntemlerini ve bağlı Amazon hizmetlerini gözden geçirin.'] }
  }
};

const TOPIC_PAGES_BATCH2 = {
  'delete-gaming-accounts': {
    kind: 'ids', value: ['steam', 'epicgames', 'playstation', 'xbox'],
    en: { title: 'Delete Gaming Accounts Without Losing Purchases | Privacy Guide', description: 'Review game libraries, licenses, wallets, inventories and linked profiles before deleting Steam, Epic Games, PlayStation or other gaming accounts.', heading: 'Delete gaming accounts without losing purchases you meant to keep', lead: 'Gaming identities can hold licenses, wallets, inventories, cloud saves, achievements and linked platform profiles. Account deletion is often more destructive than deleting a game.', sections: [['Check licenses and non-transferable purchases', 'Do not assume games, keys, subscriptions or virtual items can move to another account. Read the service guide and use any supported transfer or backup option before deletion.'], ['Protect saves, balances and security recovery', 'Review cloud saves, wallet balances, inventory, subscriptions, two-factor authentication and linked console or publisher accounts before you submit a deletion request.']] },
    ar: { title: 'حذف حسابات الألعاب بدون خسارة المشتريات | دليل الخصوصية', description: 'راجع مكتبات الألعاب والتراخيص والمحافظ والمخزون والحسابات المرتبطة قبل حذف Steam أو Epic Games أو PlayStation وغيرها.', heading: 'حذف حسابات الألعاب بدون خسارة مشتريات كنت تريد الاحتفاظ بها', lead: 'قد تحتوي حسابات الألعاب على تراخيص وأرصدة ومخزون وحفظ سحابي وإنجازات وحسابات منصات مرتبطة. حذف الحساب أوسع من حذف لعبة.', sections: [['راجع التراخيص والمشتريات غير القابلة للنقل', 'لا تفترض أن الألعاب أو المفاتيح أو الاشتراكات أو العناصر الرقمية يمكن نقلها إلى حساب آخر. اقرأ دليل الخدمة واستخدم أي خيار نسخ أو نقل مدعوم قبل الحذف.'], ['احمِ ملفات الحفظ والأرصدة والاسترداد', 'راجع الحفظ السحابي ورصيد المحفظة والمخزون والاشتراكات والمصادقة الثنائية والحسابات المرتبطة قبل إرسال طلب الحذف.']] },
    fr: { title: 'Supprimer des comptes de jeux sans perdre ses achats | Guide de confidentialité', description: 'Vérifiez bibliothèques, licences, portefeuilles, inventaires et profils liés avant de supprimer Steam, Epic Games, PlayStation ou d’autres comptes.', heading: 'Supprimer des comptes de jeux sans perdre les achats à conserver', lead: 'Les comptes de jeux peuvent contenir licences, soldes, inventaires, sauvegardes cloud, succès et profils liés. Leur suppression est souvent bien plus large que désinstaller un jeu.', sections: [['Vérifiez licences et achats non transférables', 'Ne supposez pas que jeux, clés, abonnements ou objets virtuels peuvent être déplacés vers un autre compte. Consultez le guide du service avant suppression.'], ['Protégez sauvegardes, soldes et récupération', 'Vérifiez sauvegardes cloud, portefeuille, inventaire, abonnements, authentification à deux facteurs et comptes liés avant la demande.']] },
    tr: { title: 'Satın Alımları Kaybetmeden Oyun Hesaplarını Silme | Gizlilik Rehberi', description: 'Steam, Epic Games, PlayStation ve diğer oyun hesaplarını silmeden önce oyun kitaplığı, lisans, cüzdan, envanter ve bağlı profilleri kontrol edin.', heading: 'Saklamak istediğiniz satın alımları kaybetmeden oyun hesaplarını silin', lead: 'Oyun hesaplarında lisanslar, cüzdan bakiyeleri, envanter, bulut kayıtları, başarımlar ve bağlı platform profilleri bulunabilir. Hesap silme oyunu kaldırmaktan çok daha kapsamlıdır.', sections: [['Lisansları ve aktarılamayan satın alımları kontrol edin', 'Oyunların, anahtarların, aboneliklerin veya sanal öğelerin başka hesaba taşınacağını varsaymayın. Silmeden önce hizmet rehberini okuyun.'], ['Kayıtları, bakiyeleri ve kurtarmayı koruyun', 'Silme talebinden önce bulut kayıtlarını, cüzdanı, envanteri, abonelikleri, iki aşamalı doğrulamayı ve bağlı hesapları gözden geçirin.']] }
  },
  'cancel-subscriptions-before-deleting': {
    kind: 'ids', value: ['spotify', 'amazon', 'apple', 'microsoft', 'discord', 'adobe', 'netflix'],
    en: { title: 'Cancel Subscriptions Before Deleting an Account | Privacy Guide', description: 'Avoid billing mistakes by separating subscription cancellation from account deletion across streaming, cloud, messaging and shopping services.', heading: 'Cancel subscriptions before deleting the account', lead: 'Account deletion and subscription cancellation are not always the same event. Verify billing separately so you do not delete an account when you only wanted to stop paying—or assume a charge stopped when it did not.', sections: [['Stop the correct billing relationship', 'Check where the subscription was purchased: directly from the provider, an app store or another marketplace. Cancel it through the billing system that actually owns the subscription.'], ['Preserve receipts and purchased access', 'Save receipts, invoices and any purchase records you need. Some services also attach purchased content, credits or future-event access to the same account.']] },
    ar: { title: 'إلغاء الاشتراكات قبل حذف الحساب | دليل الخصوصية', description: 'تجنب أخطاء الفوترة عبر فصل إلغاء الاشتراك عن حذف الحساب في خدمات البث والسحابة والمراسلة والتسوق.', heading: 'ألغِ الاشتراكات قبل حذف الحساب', lead: 'حذف الحساب وإلغاء الاشتراك ليسا دائماً نفس الإجراء. تحقق من الفوترة بشكل منفصل حتى لا تحذف حساباً وأنت تريد فقط إيقاف الدفع أو تفترض أن الرسوم توقفت.', sections: [['أوقف علاقة الفوترة الصحيحة', 'تحقق من مكان شراء الاشتراك: من المزود مباشرة أم من متجر التطبيقات أو سوق آخر، ثم ألغِه من نظام الفوترة الذي يديره فعلياً.'], ['احتفظ بالإيصالات والوصول المدفوع', 'احفظ الإيصالات والفواتير والسجلات المهمة. بعض الخدمات تربط المحتوى المشترى أو الأرصدة أو تذاكر مستقبلية بنفس الحساب.']] },
    fr: { title: 'Annuler les abonnements avant de supprimer un compte | Guide', description: 'Évitez les erreurs de facturation en séparant l’annulation d’un abonnement de la suppression d’un compte.', heading: 'Annuler les abonnements avant de supprimer le compte', lead: 'La suppression du compte et l’annulation de l’abonnement ne sont pas toujours la même action. Vérifiez la facturation séparément pour éviter une fermeture inutile ou des frais inattendus.', sections: [['Annulez auprès du bon système de facturation', 'Vérifiez où l’abonnement a été acheté : directement, via un app store ou une autre place de marché, puis annulez auprès du système concerné.'], ['Conservez reçus et accès achetés', 'Sauvegardez reçus, factures et preuves d’achat utiles. Certains services associent également contenu acheté, crédits ou billets futurs au même compte.']] },
    tr: { title: 'Hesabı Silmeden Önce Abonelikleri İptal Etme | Gizlilik Rehberi', description: 'Yayın, bulut, mesajlaşma ve alışveriş hizmetlerinde abonelik iptali ile hesap silmeyi ayırarak faturalandırma hatalarından kaçının.', heading: 'Hesabı silmeden önce abonelikleri iptal edin', lead: 'Hesap silme ve abonelik iptali her zaman aynı işlem değildir. Yalnızca ödemeyi durdurmak isterken hesabı silmemek veya ücretin durduğunu yanlış varsaymamak için faturalandırmayı ayrıca kontrol edin.', sections: [['Doğru faturalandırma ilişkisini durdurun', 'Aboneliğin sağlayıcıdan, uygulama mağazasından veya başka bir pazaryerinden nerede satın alındığını kontrol edin ve gerçek faturalandırma sisteminden iptal edin.'], ['Makbuzları ve satın alınmış erişimi koruyun', 'Gerekli makbuzları, faturaları ve satın alma kayıtlarını kaydedin. Bazı hizmetler satın alınan içerik, kredi veya gelecekteki etkinlik erişimini aynı hesaba bağlar.']] }
  },
  'protect-cloud-data-before-deletion': {
    kind: 'ids', value: ['google', 'microsoft', 'apple', 'dropbox'],
    en: { title: 'Protect Cloud Data Before Deleting Google, Microsoft or Apple Accounts | Guide', description: 'Back up cloud photos, files, email and recovery information before deleting an ecosystem account that controls multiple services.', heading: 'Protect cloud data before deleting an ecosystem account', lead: 'Large identity accounts can control email, cloud storage, photos, devices and sign-in relationships at the same time. Export first and verify what the account owns before permanent deletion.', sections: [['Inventory the ecosystem before deletion', 'List email, files, photos, calendars, devices, app sign-ins and shared resources that depend on the account. A single deletion action can affect several products at once.'], ['Download and verify the archive', 'Request the provider’s data export, wait for it to finish, download it and verify the important files before starting account deletion.']] },
    ar: { title: 'حماية البيانات السحابية قبل حذف Google أو Microsoft أو Apple | دليل', description: 'انسخ الصور والملفات والبريد ومعلومات الاسترداد قبل حذف حساب أساسي يتحكم بعدة خدمات.', heading: 'احمِ بيانات السحابة قبل حذف حساب منظومة كاملة', lead: 'قد يتحكم الحساب الأساسي في البريد والتخزين والصور والأجهزة وعلاقات تسجيل الدخول معاً. صدّر البيانات وحدد ما يملكه الحساب قبل الحذف النهائي.', sections: [['اعمل جرداً للمنظومة قبل الحذف', 'راجع البريد والملفات والصور والتقويم والأجهزة وتسجيلات الدخول والموارد المشتركة التي تعتمد على الحساب. إجراء حذف واحد قد يؤثر على عدة منتجات.'], ['نزّل الأرشيف وتأكد منه', 'اطلب تصدير البيانات من المزود وانتظر اكتماله ثم نزّله وتأكد من الملفات المهمة قبل بدء حذف الحساب.']] },
    fr: { title: 'Protéger les données cloud avant de supprimer Google, Microsoft ou Apple | Guide', description: 'Sauvegardez photos, fichiers, e-mails et données de récupération avant de supprimer un compte d’écosystème contrôlant plusieurs services.', heading: 'Protéger les données cloud avant de supprimer un compte d’écosystème', lead: 'Un grand compte d’identité peut contrôler e-mail, stockage cloud, photos, appareils et connexions à la fois. Exportez les données avant toute suppression définitive.', sections: [['Inventoriez l’écosystème', 'Listez e-mails, fichiers, photos, calendriers, appareils, connexions et ressources partagées dépendant du compte. Une seule suppression peut toucher plusieurs produits.'], ['Téléchargez et vérifiez l’archive', 'Demandez l’export du fournisseur, attendez sa préparation, téléchargez-le et vérifiez les fichiers importants avant de lancer la suppression.']] },
    tr: { title: 'Google, Microsoft veya Apple Hesabını Silmeden Önce Bulut Verilerini Koruma | Rehber', description: 'Birden fazla hizmeti yöneten ana hesabı silmeden önce bulut fotoğraflarını, dosyaları, e-postayı ve kurtarma bilgilerini yedekleyin.', heading: 'Ekosistem hesabını silmeden önce bulut verilerini koruyun', lead: 'Büyük kimlik hesapları e-posta, bulut depolama, fotoğraflar, cihazlar ve giriş bağlantılarını aynı anda kontrol edebilir. Kalıcı silmeden önce dışa aktarın ve kapsamı doğrulayın.', sections: [['Silmeden önce ekosistemin envanterini çıkarın', 'Hesaba bağlı e-posta, dosya, fotoğraf, takvim, cihaz, uygulama girişi ve paylaşılan kaynakları listeleyin. Tek silme işlemi birden fazla ürünü etkileyebilir.'], ['Arşivi indirip doğrulayın', 'Sağlayıcının veri dışa aktarımını isteyin, tamamlanmasını bekleyin, indirin ve hesap silmeye başlamadan önce önemli dosyaları kontrol edin.']] }
  },
  'account-deletion-grace-periods': {
    kind: 'ids', value: ['facebook', 'discord', 'microsoft', 'snapchat', 'spotify'],
    en: { title: 'Account Deletion Grace Periods: When Can You Recover an Account? | Guide', description: 'Compare services that provide a cancellation, deactivation or reopen period after account deletion begins and learn what to do before the deadline.', heading: 'Understand the recovery window before account deletion becomes permanent', lead: 'Some services make deletion immediate, while others first schedule, deactivate or mark the account for closure. The exact window matters if you change your mind or still need to export data.', sections: [['A grace period is not a backup plan', 'Use the recovery window only as a safety net. Export important information and resolve billing before starting deletion rather than assuming you can always reverse it later.'], ['Recovery rules differ by service', 'Facebook, Discord, Microsoft, Snapchat and Spotify use different cancellation or reactivation windows. Open the individual service guide for the current provider-specific rule.']] },
    ar: { title: 'فترات التراجع عن حذف الحساب: متى يمكن استعادة الحساب؟ | دليل', description: 'قارن الخدمات التي تمنح فترة إلغاء أو تعطيل أو إعادة فتح بعد بدء الحذف واعرف ماذا تفعل قبل انتهاء المهلة.', heading: 'افهم نافذة الاسترداد قبل أن يصبح حذف الحساب نهائياً', lead: 'بعض الخدمات تجعل الحذف مباشراً، وأخرى تبدأ بجدولة أو تعطيل أو وضع الحساب للإغلاق. معرفة النافذة مهمة إذا غيرت رأيك أو بقي لديك بيانات تحتاجها.', sections: [['فترة التراجع ليست بديلاً عن النسخة الاحتياطية', 'استخدم نافذة الاسترداد كشبكة أمان فقط. صدّر البيانات وعالج الفوترة قبل الحذف بدلاً من الاعتماد على إمكانية التراجع دائماً.'], ['قواعد الاسترداد تختلف حسب الخدمة', 'تستخدم Facebook وDiscord وMicrosoft وSnapchat وSpotify فترات مختلفة للإلغاء أو إعادة التفعيل. راجع دليل الخدمة لمعرفة القاعدة الحالية.']] },
    fr: { title: 'Délais de récupération après suppression de compte | Guide de confidentialité', description: 'Comparez les services offrant une période d’annulation, désactivation ou réouverture après le début de la suppression.', heading: 'Comprendre la fenêtre de récupération avant la suppression définitive', lead: 'Certains services suppriment immédiatement, d’autres programment ou désactivent d’abord le compte. La fenêtre exacte est importante si vous changez d’avis ou devez encore exporter des données.', sections: [['Le délai de grâce ne remplace pas une sauvegarde', 'Utilisez la récupération comme filet de sécurité. Exportez les informations et réglez la facturation avant la suppression au lieu de compter sur un retour garanti.'], ['Les règles varient selon le service', 'Facebook, Discord, Microsoft, Snapchat et Spotify utilisent des délais différents. Consultez le guide de chaque service pour la règle actuelle.']] },
    tr: { title: 'Hesap Silme Geri Dönüş Süreleri: Hesap Ne Zaman Kurtarılabilir? | Rehber', description: 'Hesap silme başladıktan sonra iptal, devre dışı veya yeniden açma süresi sunan hizmetleri karşılaştırın ve süre dolmadan ne yapacağınızı öğrenin.', heading: 'Hesap silme kalıcı olmadan önce geri dönüş penceresini anlayın', lead: 'Bazı hizmetler hesabı hemen silerken bazıları önce planlar, devre dışı bırakır veya kapanmaya işaretler. Fikrinizi değiştirirseniz ya da veri indirmeniz gerekirse süre önemlidir.', sections: [['Geri dönüş süresi yedek yerine geçmez', 'Bu süreyi yalnızca güvenlik ağı olarak kullanın. Her zaman geri dönebileceğinizi varsaymak yerine silmeden önce verileri dışa aktarın ve faturalandırmayı çözün.'], ['Kurallar hizmete göre değişir', 'Facebook, Discord, Microsoft, Snapchat ve Spotify farklı iptal veya yeniden etkinleştirme süreleri kullanır. Güncel kural için hizmet rehberini açın.']] }
  }
};

module.exports = { GUIDE_CONTENT_BATCH2, TOPIC_PAGES_BATCH2 };
